### ISSUE TITLE
Probleme setting

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#100]
Bon ca fait un moment que je me casse la tete dessus.
En fait apres une mise a jour des sources l'icone "MAJ dispo" reste affichée, jusque la c'est normal faudrait mettre un refresh() mais elle reste aussi apres un redemarrage.
Donc j'ai commencé quelques test et dans about.py ligne 218
>>             cConfig().setSetting('home_update', str('false'))
            #rajout
            print 'ok'
            print cConfig().setSetting('home_update', str('false'))
            print cConfig().getSetting('home_update')
            print cConfig().setSetting('home_update', str('false'))
            print cConfig().getSetting('home_update')
            #fin des rajouts
            cConfig().createDialogOK(sContent)

Voila le resultat
>>11:38:24 T:1432  NOTICE: ok
11:38:24 T:1432  NOTICE: None
11:38:24 T:1432  NOTICE: true
11:38:24 T:1432  NOTICE: None
11:38:24 T:1432  NOTICE: true

SetSetting ne change aucune valeur meme pas le md5

**Comment by LordVenom** [comment]
Depuis la mise ajour chez moi le "mise a jour" sur la page d'accueil disparais bien.

**Comment by TmpName** [comment]
Bon ok, je fais des recherches chez moi alors ....

Sinon question con, quand je fais une MAJ sur la version off sur les sites, me faut modifier le md5 par un truc au pif ? Justement pour faire apparaitre cette option ?

**Comment by LordVenom** [comment]
Oui c'est juste un comparer donc tu modifie le md5 n'importe comment et ça marque.

**Comment by TmpName** [comment]
Rien a faire,j'ai refait un test en reel, chez moi ca reste a false.
Ca ne vient probablement pas du code, mais y a un truc chelou.
