### ISSUE TITLE
Erreur Script vStream

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#111]
Je viens d'installer la beta, mais malheureusement impossible de lancer des films sur tous les sites donc impossible d'accéder aux hosters? J'ai l'erreur Script! vstream. 
Pour info ce problème a apparu seulement aujourd'hui donc il s'agit des updates effectués ce jour.
Merci de votre aide

**Comment by Kodigoal** [comment]
Salut,
oui, c'est de ma faute :p 
Petite erreur de majuscule dans le fichier /lib/gui/hoster.py ligne 146.
Mis un pull request pour correction, désolé.
