### ISSUE TITLE
Utiliser github

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons-beta#114]
Si qqn pouvait m'expliquer comment directement éditer des .py sur le github de la beta... Je n'ai jamais pratiqué... Merci pour les explications.

**Comment by TmpName** [comment]
Quand tu te trouve sur un fichier, en haut tu as 3 boutton Raw/blame/history puis 3 icones, la deuxieme te permet d'editer le fichier.
Si LordVenom t a valide l'acces c'est direct, sinon ca lance une requete qui doit etre validée.

**Comment by LordVenom** [comment]
Je tes ajouter des permissions @chataigne73.
