### ISSUE TITLE
lancer un site dès le lancement de vstream

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons-beta#120]
comme pourrais je lancer automatiquement un site (zone-telechargement au hasard) dès le lancement de vstream (au lieu de tomber sur la page d'accueil de vstream

merci

**Comment by mino60** [comment]
pour la configuration on peux faire ça mais il reste de trouver le chemin pour cela , édité le fichier home.py et ajouté une ligne don le fichier langage (setings.xml) : 

http://pastebin.com/zWMeWezt

    
    <string id="30119">Zone-telechargement</string>
