### ISSUE TITLE
Papystraming.com/fr nouvelle source

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons-beta#121]
Bonsoir je cherche le regx de cette source j'ai essayé plusieurs Pattern mais son suxé pour affiché la list des films et je confirme papystreaming.com (ENG) et papystreaming.com/fr (FRA) marche trés bien sur mediaportal et voila son code
http://pastebin.com/NWykehyH
Papystreaming_com.py
http://pastebin.com/SwfhybLd

**Comment by TmpName** [comment]
Ne perd pas de temps, papystreaming ne vaut rien.
Je ne sais pas si ca a chnage, mais la derniere fois, les liens venaient de cacaoweb, et etaient limite en temps a chaque fois.

Si tu cherches des sources a faire https://github.com/LordVenom/venom-xbmc-addons-beta/issues/86
