### ISSUE TITLE
hdstreaming.me 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons-beta#122]
voila je travail depuis hier sur cette source et je parviens pas à trouver le bon regx de ce site est ce que j'ai un problème dans les entrée ou une mauvaise pattern merci de bien vouloir expliquer comment faire pour trouver le code  comme dit le proverbe chinois : " ne me donne pas le poisson mais apprend mois commment le pêcher" .

http://pastebin.com/BYeReD4Z

**Comment by TmpName** [comment]
Ce code devrait marcher.
Il va te falloir chnager le nom en hdstreaming.py (faut virer le .me), jamais de '.' dans le nom.

Par contre j'ai testé le site, je sais pas si c'est videomega qui etait out lors de mes tests mais pas un lien n'a voulu marcher.

**Comment by mino60** [comment]
Je l'ai essayé mais il ne fonctionne pas un message kodi:  Erreur vstream consultez le journal pour +info

http://pastebin.com/Z6H5jmEA

**Comment by TmpName** [comment]
Probleme de nom, ton fichier ne s'appelle pas hdstreaming.py

**Comment by mino60** [comment]
c'est corrigé tout marche bien sau le next page et la fonction recherche

pour next page j'ai éssayé ce code normalement il est just mais problème de connection pour affiché la dexième page 
    sPattern = '<a class="page larger" href="(.+?)">'

**Comment by Kodigoal** [comment]
Pattern bon mais faut changer le sUrl aussi:
sUrl = aResult[1][0]

Sinon les liens videoMega s'ouvre pas non plus.. a voir.

**Comment by TmpName** [comment]
Mais ce site marche chez vous ?
Moi j'ai pas un lien qui marche.

**Comment by Kodigoal** [comment]
De mon côté , idem , sur le site en direct aucune vidéo s'ouvre ...
