### ISSUE TITLE
Megastream.fr

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons-beta#123]
Voila une autre source du site mega-stream.fr bon site pour streaming hd , mais toujour un probleme avec le code regex

http://pastebin.com/S2MdscV3

**Comment by TmpName** [comment]
Ce n'est pas un probleme de regex.
>>AttributeError: 'module' object has no attribute 'showMoviesNews' 

Il n'y a nulle par la fonction 'showMoviesNews'

**Comment by mino60** [comment]
j'ai corrigé l'erreur mais le regex ne fonctionne pas désormais la liste des films ce charge mais rien ne s'affiche peut être il faut faire comme filmstreamingvk ou full-streamvk.com car l'url et les images leur manque l'url main c'est pour cela qu'il ne s'affiche pas
   `` sPattern = '<a.+?href="(.+?)"><img src="(.+?)">.+?<h3>(.+?)<h3>'
une question pour quoi quand je mais le code html don le site regex101.com il me donne pas la pattern comme (.+?) à la place il me donne le non du site

**Comment by Kodigoal** [comment]
Salut,
Testé en changeant la pattern, ca liste et affiche les 20  premiers films , pour le Next je sais pas
comment faire vu qu'il faut scroller pour voir la suite et non cliquez sur page2 ou suivant..
Si ya un moyen ? 
J'ai juste mis pour lister film nouveautés/films source  pour tester:
http://pastebin.com/4JJWBdrB
J'ai pris source film streaming co vite fait car sur ton fichier, même en changeant pattern et autres parties,
ca liste mais ca n'affiche rien , pas trouvé le truc qui cloche.
Si ca peut t'aider...

**Comment by TmpName** [comment]
Je l'ai un peu avancé, vu la complexite.
Le next page fonctionne.
On peu lancer quelques videos.
Debut de l'affichage de la langue (il ya un regex qui recupere la langue dans le code mais m'en sert pas encore)

https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/megastream.py

Par contre, il y a un fichier squelette pour faire des sources, si vous partez de celui la ca m'evite d'avoir a effacer 30/100 du code a chaque fois car les sources deja finies ont du code qui leur est propre et qui ne sert a rien sur une autre.

**Comment by Kodigoal** [comment]
Epaté par le code du Next ^^ merci.

**Comment by mino60** [comment]
Bonsoir...j'ai testé le code beta mais  j'ai trouvé deux erreur 
1- la video ne ce lance pas 
http://pastebin.com/4tXJrJwL
2- la fonction Next poage ne marche pas 
http://pastebin.com/nVNHMUWK

**Comment by Kodigoal** [comment]
De mon côté , ca fonctionne les vidéos et le Next page.

**Comment by mino60** [comment]
effectivement c'est mois qui avais un problème de connexion c'est bon maintenant j'ai ajouté les deux section series anims
le résumé ne s'affiche pas je crois qu'il faut attendre la mise à jour du fichier metahandler

http://pastebin.com/Hs3Akxjh

**Comment by TmpName** [comment]
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/megastream.py

Nouvelle version avec resume, langue, selection d'episode, debut de la recherche (pas finis)

**Comment by TmpName** [comment]
Y a plus personne de motive pour cette source ?

**Comment by mino60** [comment]
j'ai essayé de trouver la pattern pour la recherche mais son succès la liste des films recherche ce charge mais elle ne s'affiche pas!?

**Comment by TmpName** [comment]
Maj https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/megastream.py

Je l'ai passe en officiel mais j'ai rate la MAJ

**Comment by mino60** [comment]
voila j'ai ajouter deux section Film HD genres et Film genres ça fonctionne plutôt bien juste un problème de Next page : exemple sur la section des films hd genre arts martiaux il ya deux films en hd
mais quand je clic sur next page je suis sur une autre page des films non arts martiaux  C'est donc qu'il ne faut pas que je trouve l'icône Next>>> qui ai en vert!..



http://pastebin.com/91VFFJBj

**Comment by Kodigoal** [comment]
Ah mince, j'ai bossé dessus pour rajouter les genres (Films/Séries/animes).
Tout a l'air de fonctionner , nextPage compris.
J'ai maj sur la beta...
Par contre j'ai pas inclus un tri Genre / Genre HD de mon côté.

**Comment by mino60** [comment]
J'ai ajouter l'affichage de l'année de sortie et la qualité d'image mais juste pour les films

http://pastebin.com/sEaJPjep

**Comment by Kodigoal** [comment]
Correction pour prise en compte du Nextpage pour les Films filtrage par genre HD.
On a par défaut 'tout_les_genres=none' ou bien pour un genre particulier 'genres[]=xx' , plus qu'a rajouter '&onlyHD=none' à la fin de l'url sNextpage pour lister seulement les HD.
Je crois qu'il reste à fignoler le regex pour le listage  des Animes qui affiche  une partie du code regex après le titre de l'anime, sinon tout a l'air ok.

**Comment by mino60** [comment]
il ya pas une solution pour corrigé le regex pour ce problème?
http://upload.dinhosting.fr/P/3/z/Sanstitre.png

**Comment by Kodigoal** [comment]
Avec la Maj de TmpName normalement c'est bon maintenant.
