### ISSUE TITLE
Poploz Le bon élève

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons-beta#124]
c'est le seul site qui n'a pas changer de non
poploz.com/dco/
Adresse IP : 23.235.206.57
Son nom d'hôte associé : vps14508.inmotionhosting.com
Pays de connexion : UNITED STATES
Ville :
FAI: InMotion Hosting
Latitude: 37.09024
Longitude: -95.71289100000001
c'est le premier site avec des films hébergé sur google  a été crée mème avant vanoz

j'ai essayé regex avec poploz ne marche pas c'est bizarre!! étant donné qu'il est juste

http://pastebin.com/tzc1qqeY

**Comment by Kodigoal** [comment]
Non ya des changements niveau des regex et code.
Fichier ok sauf recherche et le Next page, ou autre à vérifier.
http://pastebin.com/buCsGNQT

**Comment by TmpName** [comment]
Il est HS a ce moment.
Mais ce n'est pas les memes sources que kepliz ?

**Comment by Kodigoal** [comment]
oui je sais :) c'était juste pour aider et m'entrainer ^^
