### ISSUE TITLE
erreur zone telechargement

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#129]
quand je lance un host j'ai un message erreur de script voici le log

13:49:04 T:6216  NOTICE: 	[PLUGIN] Vstream: load site zone_telechargement_com and call function Display_protected_link
13:49:04 T:6216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'aResult_dlprotect' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 169, in <module>
                                                main()
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 81, in parseUrl
                                                exec "plugin."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\venom\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\zone_telechargement_com.py", line 590, in Display_protected_link
                                                if (aResult_dlprotect[0]):
                                            UnboundLocalError: local variable 'aResult_dlprotect' referenced before assignment
                                            -->End of Python script error report<--

Note : Impossible de trouver les information par le menu context le titre et envoyer en full il recherche par exemple avatar dvdrip son french donc pas de resultat.

**Comment by sebi0606** [comment]
Je ne suis pas le seul donc ....

**Comment by sebi0606** [comment]
TmpName toi aussi message d'erreur vstream quand tu essayes de lancer un film ou une serie sur zone de telechargement ?

**Comment by chataigne73** [comment]
oui oui c'est OUT pour tout le monde
car dl-protect vient de faire de grosses modifications
tmpname certainement nous corriger ça quand il pourra ;)

**Comment by sebi0606** [comment]
Merci pour l'astuce chataigne73 ;)

**Comment by TmpName** [comment]
J'ai deja ete voir pour pyload, ainsi que jdownloader.
Alors je peux me tromper, mais aucun ne marche en ce moment, certains lancent le navigateur pour fonctionner, si quelqu'un peut me confirmer.
Mais de mon cote ca avance, il me reste plus que 2 magics numbers a trouver, l'interface fonctionne deja.

L'un d'entre eux et un code anti bot, mais quelqu'un a deja bosse dessus donc vais voir si ca peut m'aider > https://github.com/toogle/InsideReCaptcha

Et le deuxieme, je ne sais pas du tout ce que c'est mais dans tout les cas il sera plus facile a trouver que le precedent.

**Comment by sebi0606** [comment]
Merci TmpName je test des que je peux et te ferai un retour

**Comment by TmpName** [comment]
Nickel.
Par contre pour eviter le doublon je ferme ce topic
Suite la bas
https://github.com/LordVenom/venom-xbmc-addons/issues/341
