### ISSUE TITLE
Sous Menu "Films"

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#130]
Avec la nouvelle beta j'ai remarqué que les sous menu de Films sont encore affiches avant les noms des sites.
A titre d'exemple quand j'accede au menu Films Nouveautés, les sites affichés sont tous précédés avec Films Nouveautés. voir ci-dessous
![screenshot_2016-04-15-19-03-02](https://cloud.githubusercontent.com/assets/9026875/14570833/1a9e8bd8-033e-11e6-9b74-be5bb374e619.png)

![screenshot_2016-04-15-19-02-47](https://cloud.githubusercontent.com/assets/9026875/14570772/dc128ffe-033d-11e6-975c-93b132c696b8.png)

Et c'est le meme cas pour tous les sous menus de la rubrique Films (Films HD, Films par genre....)

Est-il possible de les supprimer?

**Comment by arzaz** [comment]
Oups, 
Désolé j'ai activé le menu déroulant.
Merci de ne pas tenir compte.

**Comment by TmpName** [comment]
Lol, il est sympa ton theme.

**Comment by LordVenom** [comment]
Il faut pouvoir envoyer l'info de la page a kodi pour ca.

Par exemple la navigation kodi donne video/vstream si ont pouvais lui envoyer film nouveauté par exemple on pourrais le virer de la navigation de vstream.

**Comment by LordVenom** [comment]
Voila c'est modifier, la couleur choisi pour les catégories sont afficher tout le temp maintenant.

Pas de mise a jour auto pour cette modif, Mise ajour officiel ce week end.

Bon Film.
