### ISSUE TITLE
Vitesse des téléchargements

### ISSUE THREAD

**Issue by Flyterz** [LordVenom/venom-xbmc-addons-beta#131]
Bonjour,

Je viens de tester la beta de vstream, plus particulièrement avec un debrideur et j'ai constaté deux petits bugs. Le debridage fonctionne très bien avec urlresolver mais seulement pour le streaming. Les liens débridés sont "castrés" quand on les télécharge directement. Je m'explique : 

Lien debridé en streaming : Vitesse de DL = 11Mbits/s
Lien debridé téléchargé : Vitesse de DL = 555Kbits/s
Lien debridé avec la fonction "DL et Visionner" = 11Mbits/s
A savoir que 11Mbits/s est ma limite perso :)

Le téléchargement fonctionne tres bien quand on le lance avec la fonction DL et Visionner ce qui est étrange. Ce n'est pas hyper handicapant puisqu'on peut annuler le visionnage et le téléchargment continue de fonctionner à pleine vitesse.

Le deuxième petit bug que j'ai remarqué est avec un compte 1fichier premium, il m'est impossible de téléchargé un fichier avec un compte premium et sans urlresolver.

En tout cas c'est un super addon merci pour tout. Et à pars ca je n'ai rien constater le captcha de Zone Telechargement fonctionne nickel. :+1:

**Comment by TmpName** [comment]
Pour la baisse de vitesse en cas de DL c'est fait expres, kodi est avant tout pour visualiser des stream pas telecharger, il y a un bridage pour pouvoir telecharger et visualiser un autre film en meme temps, pour eviter que le DL bouffe toute la bande passante. Il n'y pas de bridage en cas de "dl+visualisation" car il faut que le DL aille au plus vite pour ne pas bloquer la visualisation.

Pour le telecharger avec un compte premiun, c'est effectivement un bug, j'y jette un oeuil de suite.

**Comment by Flyterz** [comment]
D'accord, je comprends mieux, merci :)
Merci pour la correction de 1fichier, je test ce soir :+1:

**Comment by spcxsat** [comment]
Hello,

Ca vient de mon installation ou j'ai l'impression que ca fonctionne plus les telechargement.

j'ai essayer sur plusieur site et il ne par plus.

kepliz, film_illimit, etc...

**Comment by TmpName** [comment]
Exact, dsl, me suis encore loupe quelque part.
15 mn, je te corrige ca.

**Comment by spcxsat** [comment]
Merci beaucoup, c'étais pas urgent.
Je ne pourrais pas teste avant demain soir, pour le retour

**Comment by spcxsat** [comment]
Nickel ca fonctionne très bien
