### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#132]
Avec la beta j'ai un problème avec la recherche de films a chaque fois que je lance une recherche ca plante "mise en cache"?
Testé sur android tv box.

**Comment by TmpName** [comment]
Ce serait pas un bug de kodi directement ?
Tu as essaye de vider des caches Kodi ou vstream ?

**Comment by arzaz** [comment]
J'ai bien vidé les caches mais le problème persiste!!!!
Il commence a faire une recherche sur 03 a 04 sites puis il plante? Ca ne sera pas un site qui bloque?
![screenshot_2016-04-22-19-01-14](https://cloud.githubusercontent.com/assets/9026875/14750656/cfe298ca-08bd-11e6-9d26-f16fdc461111.png)

**Comment by TmpName** [comment]
Quelqu'un a un probleme senblable au tiens > https://github.com/LordVenom/venom-xbmc-addons/issues/355

Un site peu bloquer oui, mais en cas d'erreur il est saute, il ne peut pas bloquer la recherche, il n'y rien dans les logs ?

**Comment by Kodigoal** [comment]
Correction sur  la source Fullmoviz , normalement en faisant la Maj de cette source , le soucis
de recherche doit être réglé.

**Comment by LordVenom** [comment]
Bonjour, 

@Kodigoal Si le fichier n'est pas sur le repo officiel et le fichier site.json corriger pas de mise a jour auto , voir https://github.com/LordVenom/venom-xbmc-addons/wiki/Mise-a-jour-(admin)

**Comment by Kodigoal** [comment]
Bonjour LordVenom,
Oui je sais , je veux dire par 'faire la maj de cette source' , mettre à jour soit même le fichier source
en se basant sur la correction dispo sur la Beta, mais c'est vrai j'ai pas bien précisé :p désolé

**Comment by LordVenom** [comment]
Lol y a pas de mal,  je ne savais pas que tu savais :+1:

**Comment by arzaz** [comment]
Tout est Ok maintenant.

Merci a vous tous
