### ISSUE TITLE
Planet Stream

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#133]
Le site planet stream est vide.

**Comment by sebi0606** [comment]
Et apparement hdstream.in le site à fermé

**Comment by TmpName** [comment]
Planet stream mit a jour.
hdstream vient de repartir.

**Comment by arzaz** [comment]
Merci de voir pourquoi les séries s'affichent avec les films?

**Comment by TmpName** [comment]
Lol, j'etais dessus hier justement, pas le choix, tout apparait en meme temps et pas moyen de trier, on pourrait faire avec le mot "saisons" mais comme ca marche tres bien .....
