### ISSUE TITLE
Metahandler

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#134]
J'ai remarqué après installation de la beta hier, que le Metahandler n'a aucun effet alors que je l'ai bien activé dans le menu.

**Comment by TmpName** [comment]
Ha mer2, c'est con ca, a 3 jours de la MAJ.
Y en a qui peuvent confirmer ? Chez moi ca tourne bien.
Tu l'as active dans quel menu ?

**Comment by arzaz** [comment]
Je l'ai activé dans --> Menu --> General --> Metahandler

Y a t-il eu une mise a jour de la beta aujourd'hui? Car je parlais de celle d'hier.

**Comment by arzaz** [comment]
Meme problème avec la dernière beta.

**Comment by LordVenom** [comment]
Chez moi aussi ça fonctionne.

**Comment by TmpName** [comment]
Tu as bien coche "recherche les metadonnees" ?

**Comment by arzaz** [comment]
Après avoir réinstallé KODI, tout est rentrée en ordre.
