### ISSUE TITLE
Fermeture de bêta

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#135]
Comme nous doublon nos post pour faire la mise a jour auto, je pense que l'on peux fermer bêta ça diminueras le travail et de toute façon temps que j'envois pas de zip et d'update les utilisateur n'auront pas de mise a jour majeur.votre avis ?

**Comment by TmpName** [comment]
Ben moi j'aime bien, tout le monde peut y balancer des trucs, meme si en realite peu le font.
C'est plus securisant, je me suis souvent plante en mettant en ligne des fichiers.
Pour les beta testeurs, ca permet de pouvoir tester une version incomplete ou buguee, sans pourrir la VO.

Mais si j'ai bien compris tu parles de garder le zip intact et de se dechainer sur "les fichiers seuls", dans ce cas je comprend l'utilite mais au niveau des accees, tu vas gerer ca comment ? Tu as moyen de permettre aux gens de modifier le code sans qu'ils puissent toucher au zip ?

On ne pourra plus faire de modifs beta sur les sources ou les hosts, car sinon lors des MAJ, si le fichier n'est pas nouveau il va se retrouver chez les users.

Pareil, au niveau securite, si tout le monde peut bidouiller les sources ou les hosts, il y a moyen de planter completement Vstream avec les MAJ auto.

**Comment by spcxsat** [comment]
Bonjour,

Moi j'aime bien la bêta même si parfois il peu y avoir un mini bug, je tourne toujours avec celle-ci.
Je pense un peu comme TmpName, sa permet de remonter un bug avant quelle arrive au utilisateur "standard"
Après je ne pensais pas que la mise a jour auto étais différente que la standard, je pensais que c'étais la même en faim de content et qu'il fallait éviter de la faire sur la bêta. Bien pour ça que je surveille pour dire presque tous les jours si il y a eu des modifications de faite sur celle-ci pour la télécharger si il y a eu et teste.

**Comment by LordVenom** [comment]
Ok je touche pas alors.
