### ISSUE TITLE
Pr info

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#136]
Nouvelle source h ttp://serie-stre aming.watch.
Rien de special dessus mais c'est la seule que j'ai trouve avec les saisons de "scooby doo where are you", a part evidement planet-serie.

**Comment by spcxsat** [comment]
Yes je vient de tester elle fonctionne bien, comme pour les autres d'ailleurs.
Merci pour cette nouvelle sources, si elle peu nous apporter des séries que l'on trouve pas ailleurs t'en mieux.
