### ISSUE TITLE
Sélectionner la vue View_53_ShowCase par défaut pour vStream

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons-beta#139]
C'est encore moi... :)

Et ce n'est peut-être pas le bon endroit pour poser cette question.

Mais existe-t'il une solution pour sélectionner une vue par défaut pour un addon et en l'occurence pour vStream :)

Dans mon cas je voudrais afficher toutes les listes de films de vstream avec la vue View_53_ShowCase

Toute aide sera la bienvenue car je mouline depuis un moment :)

Merci d'avance.

**Comment by TmpName** [comment]
Ben dans la mesure ou Vstream ne la chnage pas, il te suffit de la selectionner 1 fois pour que cela soit memorise, par contre a cause du next page, il va te falloir recommencer l'operation plusieurs fois.

Si tu veut que cela soit automatique, je pense que le seul moyen est de modifier chaque fichier sites.

Peut etre en rajoutant la fonction dans oGui.setEndOfDirectory() vu que cette fonction est (presque) appelle a chaque fois en fin d'affichage.

**Comment by canopre** [comment]
Merci pour ta réponse :

> Peut etre en rajoutant la fonction dans oGui.setEndOfDirectory() vu que cette fonction est (presque) appelle a chaque fois en fin d'affichage.

Mais peux-tu m'en dire plus stp ?

**Comment by LordVenom** [comment]
Je suis pas pour forcer l'affichage mais j'avais pas penser au next page, donc la seul solution c'est de créer un réglage dans les paramettre de l'addon.

**Comment by TmpName** [comment]
Ben vais faire mon boulet, mais perso le seul endroit ou je trouve ca plus esthétique c'est sur la page home.
C'est un prb pr le next page, mais suffit de le faire 4 /5 fois et c'est bon, moi perso je ne vais jamais plus loin que la 3 eme pages.

On peut faire une option dans VStream pour les forcer, mais on ne va pas en faire une par sites, et autant certains sites peuvent tourner avec la totale, d'autres n'ont pas de resume ou meme pas d'affiche donc pour ces sources afficher les infos ou vignettes, bof.

La je t'avous, je sais pas si c'est utile.

**Comment by LordVenom** [comment]
J'ai fait un truc super jolie avec les options des vues puis une fonction pour trouver la bonne vue ça ma pris une plombe....

Pour ensuite tester et me rendre compte que les thèmes utilise pas les même id pour les vues.

Donc un simple numéro seras dispo j'ai quand même mis les vues les plus courante en info vous pourrais modifier pour les films, les series, et le reste.

**Comment by TmpName** [comment]
XD, je compatis
Vais tester ca demain.

**Comment by canopre** [comment]
Bonjour,

Si je peux donner mon avis de simple utilisateur qui n'y comprends rien au code :
Un réglage dans l'addon semble le + pratique car en fonction de l'utilisation il peut y avoir bcp plus que 4 ou 5 pages à configurer.

**Comment by spcxsat** [comment]
Yes pour les vue la je vous rejoind ca serais top de pouvoir les configurer en option pour tous les sites identique

**Comment by LordVenom** [comment]
Y a 4 reglage, films, series, autre, accueil.

**Comment by spcxsat** [comment]
Yes je vient de voir ca.
Mais je voie que vous mettez en exemple que 5 réglages pour film entre autre..
Les autres vue ne fonctionne pas où sais que des exemple?
Merci

**Comment by LordVenom** [comment]
C'est celle qui sont le plus compatible avec les themes. Comme chaque theme utile une ID différente à vous de voir quel id il vous faut.

**Comment by spcxsat** [comment]
OK merci

**Comment by canopre** [comment]
> Y a 4 reglage, films, series, autre, accueil.

0n les trouves où ces réglages svp ?

**Comment by spcxsat** [comment]
Paramètre accueil

**Comment by canopre** [comment]
Vous pouvez m'envoyer votre settings.xml svp car moi j'ai pas tout ca  :)

Merci d'avance.

**Comment by TmpName** [comment]
Ca ne marchait pas avec celui la ?
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/settings.xml

**Comment by canopre** [comment]
Salut et désolé pour ma réponse tardive.
Merci pour le fichier : je ne sais pas pourquoi mais le mien était bcp + petit.
Pourtant je ne vois toujours pas comment régler les vues dans la configuration de vstream.

Je vais tenter une nouvelle installation pour tout mettre propre.

**Comment by canopre** [comment]
Hello.

Après de nombreux essais : j'ai remarqué que les widgets ne s'affichaient pas si tu utilises comme source la "recherche visuelle" de vstream.

C'est peut-être ca ton problème ?
