### ISSUE TITLE
Petit soucis avec une source

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons-beta#140]
J'ai un petit soucis avec la source voir_films

Quand je sélectionne les nouvelles séries + sources

La première page de résultat affiche bien des séries mais à partir de la suivant ce ne sont plus que des films.

C'est pas très grave mais parfois dommage car cette source fonctionne assez bien.

Merci d'avance.

**Comment by LordVenom** [comment]
Merci, c'est corriger en envoyer en mise ajour.

**Comment by canopre** [comment]
Cool !
Et encore merci pour votre réactivité !

**Comment by canopre** [comment]
Hello

Je ne sais pas exactement ce qui c passé mais j'ai lancé une mise à jour des hosts dans vtream et maintenant  la source voir_films n'est plus dutout disponible dans Séries.

Merci d'avance.

**Comment by LordVenom** [comment]
Pas de soucis chez moi

**Comment by canopre** [comment]
non aucun message d'erreur : le host n'est simplement plus disponible (visible) dans aucune des listes de séries (nouveautés, populaires, genres).

**Comment by TmpName** [comment]
Meme pas dans "sources" ?

**Comment by canopre** [comment]
Et non : Même pas dans les sources :(

**Comment by TmpName** [comment]
Normallmeent tu devrais voir un truc de ce genre
>>17:27:06 T:2504  NOTICE: 	[PLUGIN] Vstream: Load Plugin filmsvostfr_org
17:27:06 T:2504  NOTICE: 	[PLUGIN] Vstream: Load Plugin film_illimit_fr
17:27:06 T:2504  NOTICE: 	[PLUGIN] Vstream: Load Plugin film_streaming_co
17:27:06 T:2504  NOTICE: 	[PLUGIN] Vstream: Load Plugin freebox
17:27:06 T:2504  NOTICE: 	[PLUGIN] Vstream: Cant import Plugin freebox

**Comment by canopre** [comment]
Désolé pour ma réponse tardive : J'ai ré-installé vstream et tout est OK maintenant.

**Comment by TmpName** [comment]
Lol, mais je te vois sur tout les post ce matin ^^.
