### ISSUE TITLE
Les Pigeons c'est relou

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons-beta#141]
Oui oui c'est encore moi :)

Avez-vous remarqué les pigeons pour toutes les vidéos hébergées chez openload ?

Ca fait 2/3 jours que ça dure et donc toutes les chances que ca soit un nouveau bug.

**Comment by TmpName** [comment]
XD, t'aimes pas les oiseaux ?
J'y jette un oeuil dessus ce soir mais LordVenom a deja commence les corrections

Suite ici
https://github.com/LordVenom/venom-xbmc-addons/issues/396#issuecomment-224670411

**Comment by canopre** [comment]
Mes excuses : je n'avais pas vu que le sujet était déjà ouvert et...fermé maintenant.
