### ISSUE TITLE
Nouvelle popup

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#142]
Bon tous ceux que j'ai tester ne fonctionne pas, Alors Je sais pas si c'est possible à regarder si ont peux faire une popup load global qui passe par exemple par _init_ de gui puis par addfolder et la fin par setEndOfDirectory la ou je bloque c'est qui ne prend plus le click impossible de garder le Annuler qu'il et obligatoire de garder.Le but au final et d'avoir une popup qui vas pouvoir load la recherche en une foix.

**Comment by TmpName** [comment]
Tu cherches a afficher les resultats de la recherche sur une fenetre de dialogue ?

**Comment by LordVenom** [comment]
Nop juste a ne plus avoir de multi progresse dans la recherche. Une simple fenêtre avec le nom du site en cour et le compteur dans l idéal.

**Comment by TmpName** [comment]
Il y a pas deja ca sur exodus ? Juste apres avoir clique sur un film ?
J'avais deja essaye a un moment de faire une seule progress bar au lieu de 10, mais j'ai laisse tomber, fallait modifier tout les fichiers sites.

**Comment by LordVenom** [comment]
J'ai fait aussi pas mal de test sans résultat.

**Comment by TmpName** [comment]
En fait tu cherches a faire le meme systeme que exodus, 1 seule progress bar qui avance selon le nbre de sources ?
Moi j'avais trouve une methode en modifiant les fonctions updateDialog/createDialog/finishDialog mais fallait modifier toute les sources, je crois en fait que je ne lancais une progress bar uniquement si la precedente etait ferme, donc si la recherche globale avait lance la sienne, les autres etaient sautee, mais c'etait un nid a bug.

Tu as lance le relooking complet de 2016 de Vstream ^^ ?

**Comment by LordVenom** [comment]
J'ai fait tellement de test que je serais plus expliquer les étapes la ou ça bloque c'est le doModal() soit la popup bug soit elle ne ce fermer plus oui ça cause trop de bug. Mais je cherche toujours lol

**Comment by spcxsat** [comment]
Hello,

J'ai vue qu'il y a eu une mise à jour pour la popup pour les recherche.
Visuellement sais pas mal par contre pour moi ca fonctionne pas ca bloc toujours sur kepliz

Bonne continuation

**Comment by LordVenom** [comment]
Ok merci je pense qu'il vas faut un peux de patience juste.

**Comment by TmpName** [comment]
Alluc redeconne chez vous ?

**Comment by spcxsat** [comment]
J'ai pas regarder pour le log et la je suis au taf donc peu pas contrôler

**Comment by spcxsat** [comment]
Yes sais bon j'ai reactiver kepliz et ca passe bien et pour Alluc pas de souci ici

**Comment by LordVenom** [comment]
@TmpName  non pas de soucis pour alluc
