### ISSUE TITLE
Widgets et Démarrage auto des films.

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons-beta#143]
Bonjour,
Certaines sources (stream_complet par exemple) permettent le démarrage automatique du film et c'est bien pratique.

Par contre si j'utilise cette source pour afficher un widget : Je ne peux plus stopper un film : Il redémarre tout seul après avoir été arrêté.

Avez-vous le même problème où ce bug concerne uniquement mon skin (Aeon Nox Silvo)

Merci d'avance pour vos commentaires et bon week end.

**Comment by TmpName** [comment]
Ha j'avais pas pense a ca.
Je sais pas ce que c'est que les widgets mais je comprend le prb.

Moi j'ai vu que a certain moment quand tu stoppes le film, ca revient juste en arriere, et d'autres fois ca recharge la page. Et dans ce cas si ca recharge la page, ca relance le film. Mais ca me derangeait pas donc j'ai pas fais cas.

Tu fais comment pr creer le widget ?

**Comment by canopre** [comment]
Bonjour,
Je joins une copie d'écran d'un widget.
http://picpaste.com/screenshot000-6Cf6s1FD.png

Pour les activer, ca se passe dans les réglages du menu principal : Je peux afficher 1 ou 2 widgets par élément du menu.

**Comment by TmpName** [comment]
C'est pas le meme fonctionnement que la library que je puise tester ?

**Comment by canopre** [comment]
Désolé mais je comprends pas la question.

**Comment by TmpName** [comment]
Tu n'as pas le meme bug avec les librairie de Vstream ?
Car je ne trouve pas ton theme et quand j'ai voulu en tester un autre , probleme de dependance.

**Comment by canopre** [comment]
Salut
as-tu réussis à afficher les widget ?
Ca se passe au niveau du la création du menu : Pour chaque ligne tu peux afficher 1 ou 2 widgets.
Bon we.

**Comment by TmpName** [comment]
Non, toujours pas , mais suis repasse a l'ancien skin pour le moment.
Par contre y a un autre topic sur les widgets > https://github.com/LordVenom/venom-xbmc-addons/issues/411

**Comment by mino60** [comment]
@TmpName  pour avoir les withgets : système - apparence - skin-En obtenir plus ...
sélectionner Aeon Nox 5: SiLVO
lorsque le skin Aeon Nox installer et activer: système Apparence- Habillage - Aeon Nox: SiLVO
Paramètres- Configure le menu principal Aeon Nox

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16541370/1b9b5590-4081-11e6-8473-a5f7ba0aad53.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16541372/2560fdbe-4081-11e6-9abb-858d6c4f1584.png)
![sans titre3](https://cloud.githubusercontent.com/assets/11494048/16541376/31651d52-4081-11e6-950c-f7031686533b.png)

**Comment by TmpName** [comment]
Bon alors j'ai teste.
Tant que tu fais defiler les film tu es sur "showmovies" et si tu choisis un film tu lances "ShowHosters", jusque la tout est normal, mais quand tu essaye de revenir, il relance "Showhosters" et meme 2 fois ??

J'ai essaye de mettre un "return" en fin de la fonction, crash de kodi carrement.

La franchement, faudrait voir comment fonctionne leur widget.

**Comment by mino60** [comment]
la solution c'est du mettre : return ' '

**Comment by TmpName** [comment]
???
Lol serieux ?
Tenez moi au courant si ca marche, put1 si c'est ca tu as gagne mon respect infini, c'est le seul truc que j'ai pas teste, tellement ca ma prit la tete.

**Comment by canopre** [comment]
Je voudrais bien aider : ch'ui la dernière des buses mais chez moi ca marche super bien, c très simple à installer et ca s'affiche tout seul...
As-tu fais des essais avec vstream comme source du widget ?

**Comment by TmpName** [comment]
Donc la modif de @mino60 suffit pr tout faire tourner ?
