### ISSUE TITLE
Icon sites

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#145]
Voila les modification apporter comme d' habitude vos remarque et réaction sont les bienvenues.

- Ca va grossir l'addon les images sont stocker en local pour un chargement plus rapide et pour calibrer correctement la taille.

![screenshot004](https://cloud.githubusercontent.com/assets/4380112/16387228/3cd5920c-3c94-11e6-9685-eb56fd6e114e.png)

**Comment by spcxsat** [comment]
Yes ça rend pas mal... jm bien

**Comment by sebi0606** [comment]
Très sympa @LordVenom je valide de mieux en mieux

**Comment by X-ardion** [comment]
Moi, je met directement les vignettes quand elles sont disponible, c'est plus convivial (ex: les chaines de télé). 
Super, je suis pour.

**Comment by TmpName** [comment]
Moi j'aime bien aussi, plus facile pr s'y reconnaitre.
Pour la taille des fichiers tu as teste plusieurs formats ou la compression ?
Rien qu'en ouvrant un fichier png de 38k, et le re-enregistrant de suite avec photofiltre je passe a 28k. Sans modifs, tjours en png.
