### ISSUE TITLE
modifs zone telechargement

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons-beta#146]
salut
je souhaite faire quelques corrections/améliorations sur ZT
question : la beta est au meme niveau que la master
je fais des modifs en beta (comme j'ai les droits) et vous les vérifierez/pousserez sur master c'est bien ça ?

**Comment by chataigne73** [comment]
bon je pensais que j'avais des pbs à cause de ZT, mais en fait non, je pense que ça vient de uptobox.py

par ex. TmpName si tu veux jeter un oeil:
dans ZT, va dans derniers concerts
selectionne le concert des redhot live at slane castle
puis choisir le lien uptobox (qui est un lien premium)
et moi j'obtiens ce log:
`Thread DVDPlayer start, auto delete: false
15:37:37 T:11248  NOTICE: Creating InputStream
15:37:37 T:11248   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www74.uptobox.com/d/5myutthsen5vobkqjdm4ufrcou7gybsd2diapj74xvx5ynbooxahgvbygqvyxk3lnstn7nnpdb7d3cnerq/Red Hot Chili Peppers - Live at Slane Castle 2003.AC-3 5.1.www.zone-telechargement.com.mkv
15:37:37 T:11248   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
15:37:37 T:11248   ERROR: CCurlFile::Open failed with code 400 for http://www74.uptobox.com/d/5myutthsen5vobkqjdm4ufrcou7gybsd2diapj74xvx5ynbooxahgvbygqvyxk3lnstn7nnpdb7d3cnerq/Red Hot Chili Peppers - Live at Slane Castle 2003.AC-3 5.1.www.zone-telechargement.com.mkv
15:37:37 T:11248   ERROR: XFILE::CFileCache::Open - failed to open source <http://www74.uptobox.com/d/5myutthsen5vobkqjdm4ufrcou7gybsd2diapj74xvx5ynbooxahgvbygqvyxk3lnstn7nnpdb7d3cnerq/Red Hot Chili Peppers - Live at Slane Castle 2003.AC-3 5.1.www.zone-telechargement.com.mkv>
15:37:37 T:11248   ERROR: CDVDPlayer::OpenInputStream - error opening [http://www74.uptobox.com/d/5myutthsen5vobkqjdm4ufrcou7gybsd2diapj74xvx5ynbooxahgvbygqvyxk3lnstn7nnpdb7d3cnerq/Red Hot Chili Peppers - Live at Slane Castle 2003.AC-3 5.1.www.zone-telechargement.com.mkv]
15:37:37 T:11248  NOTICE: CDVDPlayer::OnExit()`

**Comment by TmpName** [comment]
Yep, la beta, on peut se lacher dessus, une fois que les modifs sont validées si c'est vraiment utile ca passe direcxt en off sinon a la prochaine maj de LordVenom.

Sinon j'ai trouve ton bug
Ce lien ne marche pas sen5vobkqjdm4ufrcou7gybsd2diapj74xvx5ynbooxahgvbygqvyxk3lnstn7nnpdb7d3cnerq/Red Hot Chili Peppers - Live at Slane Castle 2003.AC-3 5.1.www.zone-telechargement.com.mkv
Mais celui la si : sen5vobkqjdm4ufrcou7gybsd2diapj74xvx5ynbooxahgvbygqvyxk3lnstn7nnpdb7d3cnerq/Red%20Hot%20Chili%20Peppers%20-%20Live%20at%20Slane%20Castle%202003.AC-3%205.1.www.zone-telechargement.com.mkv

Encore un qui ne sait pas qu'on ne met jamais d'espace ou de caractere accentue dans un nom de fichier.
Faut soit remplacer  les espaces par des %20 soit encoder tout les lien pour les prochaine fois.

**Comment by TmpName** [comment]
Dans uptobox.py
l175
return urllib.quote(aResult[1][0])

**Comment by chataigne73** [comment]
J'ai rencontré des pbs sur plusieurs films récemment, c'est ce qui m'a décidé à regarder pour comprendre.
C'est cool que tu aies trouvé la raison.
Je vote aussi pour le 2

**Comment by chataigne73** [comment]
et oui la plupart des sites renomment les fichiers avec des noms courts et sans caracteres exotiques

en tous cas je te confirme que sur uptobox je rencontre assez régulièrement le pb
autre exemple rencontré récemment ici `http://uptobox.com/0b8fs22b72hm`

**Comment by TmpName** [comment]
En fait j'ai vraiment peur pr le (1) car ca risque de faire buguer les autres, en l'absence de cas je pense qu'on va rester sur le (2)

**Comment by chataigne73** [comment]
mince j'ai modifié par erreur un de tes commentaires !  dsl
là où je dis que cette solution ne fonctionne pas, car cela modifie aussi le : de http://

**Comment by chataigne73** [comment]
je propose donc `return urllib.quote(aResult[1][0], safe=":/")`

**Comment by TmpName** [comment]
Lol decidement.
Il y a aussi le replace(' ','%20') qui est plus rapide en python, mais faut etre sur qu'un artiste ne va pas en profiter pour utiliser un autre caractere a la con.
