### ISSUE TITLE
Question de Noob .... Encore une fois !

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons-beta#148]
Pour commencer : 1000 mercis pour cet addon : mes remarques ne sont pas des critiques mais juste des questions de noob, en espérant faire avancer le schmilblick mais comme je n'ai aucune compétence en codage : je n'ai aucune notion de la possibilité de mes demandes ou même si c'est juste seulement possible.

Toutefois : comme j'utilise aussi des addons pour des films en Anglais : Comme "Specto Fork" : je me demandais pourquoi pour les films en francais c'est si compliqué pour l'utilisateur :

Avec les films en Anglais, en configurant l'addon sur "Autoplay" : L'adon sélectionne la meilleure source et la démarre sans autre intervention.

Pourquoi on peut pas faire pareil en Français ?

Merci d'avance pour vos explications et bon week end.

**Comment by TmpName** [comment]
Tout simplement parce que l'humain est plus efficace et plus rapide que la machine pour choisir la meilleure source.
Comment tu programmerais Vstream pour choisir la meilleure source ?

Youwatch est au top a 8h de matin a chier a 21h
Openload est au top en general, mais quand ils reprotegent leur site tu as des pigeons pendant plusieurs jours.
Tu ne peux pas savoir a 100/100 si une source est morte ou pas sans faire de requetes, donc faudrait tester toutes les sources, y compris les chat noirs qui bloquent tout.
Parfois je cherche un apercu du film donc me faut du SD, parfois je le lance sur video projecteur donc HD.
Par experience, certaines series sont supprimes sur certains hebergeurs, mais pas d'autres.

Certains sites ont les liens proteges, donc faut attendre 6/10s avant d'avoir les liens, multiplis par le nombre de liens possibles.

LordVenom a choisit le solution qui marchera le mieux, pareil c'est al utilisateur de verifier le nom du film avant de le lancer contrairement a ExodusFR qui du coup ne garantit plus ce que tu va obtenir a la fin.
Toi ca te coute 5s de ton temps pr lire et choisir.

En resume c'est juste un choix, pour etre sur que cela va marcher.

**Comment by canopre** [comment]
Super ! Merci : Je comprends mieux maintenant.
