### ISSUE TITLE
Modif du fichier lib/gui/hoster.py

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#15]
http://pastebin.com/2bizj0FH

def checkHoster(self, sHosterUrl): 
    
        sHosterUrl = sHosterUrl.replace('.','') =>je suis obligé de mettre ca pour faire fonctionner le hoster 'videott'

**Comment by TmpName** [comment]
Ha, c'est un reliquat d'un de mes codes que j'ai eu la flemme de tester, en fait moi je teste 'videott' par exemple mais si on met

if 'video.tt'=' in truc

ca devrait marcher aussi, j'ai pas testé par contre.

**Comment by FreeFighter77** [comment]
Je confirme: 

if ('video.tt' in sHosterUrl):
            return cHosterHandler().getHoster('videott')

**Comment by TmpName** [comment]
Venom a mit le fichier hosters.gui, on va pouvoir commencer les modifs dessus.

**Comment by FreeFighter77** [comment]
Je peux deja te dire que pour speedvideo ca va fonctionner pour voirfilms.org, mais pas pour streamzer.net (ex:fast and furious 7) car l adresse a cette forme:
http://speedvideo.net/embed-4nfb6zgfuiq0-640x391.html

**Comment by LordVenom** [comment]
Je vous est passer tous les 2 en collaborateur, je sais pas trop quel droit ça vous donne j'espere suffisant pour que vous validiez les pull request.

Il vaut mieux dans le hoster mettre if lurl.com est faire un autre if lurl.net que cherche a compliquer le code.

**Comment by FreeFighter77** [comment]
yep c est ce que j ai fais chez moi ca tourne nickel:
if ('http://speedvideo.net/embed' in sHosterUrl):
            return cHosterHandler().getHoster('speedvideo')
if ('http://www.speedvid.net/embed-' in sHosterUrl):
            return cHosterHandler().getHoster('speedvid')

voila ;) speedvid tu peux le test sur series fr.com, et speedvideo de cet forme sous streamzer.net (ex:fast and furious 7) . Je sais je radote

**Comment by LordVenom** [comment]
Le embed et embed- et vraiment nécessaire ?

**Comment by FreeFighter77** [comment]
non,c un oublie ;)
