### ISSUE TITLE
frenchstream.org

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#20]
Je pense qu'il faudrait retirer la section série,car il n y a qu'un seul hoster et il est bien souvent mort,ça éviterais les questions ultérieur: ca marche pas ^^ (ce site est magnifique pour les films malheureusement pour l instant cote serie ...) qu en pensez vous ? (un ptit # et hop)

**Comment by LordVenom** [comment]
Si les liens sont souvent HS et qu'il y a une source mieux qui tourne oui ont peux la masquer.
