### ISSUE TITLE
Incorporer les fonctions utiles dans le code de Vstream.

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#21]
Certaines fonctions servent souvent comme unescape qui sert a convertir les codes html comme "&#123". ce serait plus simple si on pouvait les rajouter dans le fichier utils.py par exemple.

**Comment by LordVenom** [comment]
Bonjour, le parser a deja une option pour ça a toi de voir comment bien l'utiliser ou même la modifier pour qu'elle fonctionne encore mieux.

**Comment by TmpName** [comment]
Pas pour recuperer les infos c'est une fonction pour nettoyer les infos apres les avoir recupéree.
En fait parfois dans les titres de fims tu en vois certains qui justement auraitent besoin de cette fonction, les titres sont bien recupéré par le parser, mais mal formaté.
