### ISSUE TITLE
Mailru

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#22]
Le host Mailru ne fonctionne plus, j'ai le message d'erreur "Echec de lecture......."
Testé avec le film Invincible de la source full-stream.me

**Comment by TmpName** [comment]
Testé a l'instant, pas de soucis pr moi.

question perso, combien de films tu regardes par jours ?

**Comment by arzaz** [comment]
01 Film

**Comment by TmpName** [comment]
Lol, je te demande ca car a chaque fois tu es le premier a voir le host deconner, moi meme pendant mes tests je vois quedale.

D'ailleurs a props de bug, tu as vu mon dernier messagesur dpstreaming.org, j'ai pas compris le dernier truc que tu as trouvé.

**Comment by TmpName** [comment]
Ha mer.. autant pour moi, je t'ai confondu avec un autre user, dsl.

**Comment by arzaz** [comment]
Pas de problème TmpName
