### ISSUE TITLE
Fullstream me

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#23]
Bonjour, la version récupéré ne fonctionner pas pour les series et les manges et les thumbs c'est chose corriger.Par contre l'ors de mes test le site ramer beaucoup trop. Au prochain test si ça rame encore il seras supprimer.

**Comment by TmpName** [comment]
Je confirme, moi j'ai meme du tuer l'application, freeze complet.
Je m 'y penche dessus, perso c'est une des sources dont je me sert le plus, ca me fairait mal ^^.
