### ISSUE TITLE
Voirfilm.org

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#27]
Bonjour, comme le site n'est pas fini par défaut il est désactiver dans les préférences, penser à activer le site pour travailler dessus. @+

**Comment by TmpName** [comment]
Ben je suis tombé dessus ce Week End, je crois qu'il etait HS pendant un moment, tout ce que je sait c'est qu'il faut le retester, j'ai du  changer tout les patterns.

Il a l'air de fonctionner, mais mino60 me trouve tjours des bugs apres mes tests.

**Comment by LordVenom** [comment]
Impossible de lancer une video erreur de script de plus il reste tout les variables de test.

**Comment by LordVenom** [comment]
Ok j'ai trouver pk 

"   fh = open('c:\\test.txt', "w")
     fh.write(sHtmlContent)
     fh.close()
"

**Comment by LordVenom** [comment]
Probleme resolut

**Comment by TmpName** [comment]
XD, dsl, j'ai du oublier ca, je m'en sert pr le deboguage.
Par contre comment cela se fait que chez toi, cela provoque un plantage ? Chez moi ca cree juste un fichier texte.

**Comment by LordVenom** [comment]
a cause des droits d’écriture.
