### ISSUE TITLE
Sites pas encore sur le/la beta

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#28]
Bon je met ma liste ici, besoin de testeurs, de memoire aucun n'est terminé donc je ne les met pas sur la beta.

Mangacity > http://pastebin.com/KwCBSPLA
KaKastream > http://pastebin.com/TBtZP4RZ

Et evidement Vanoz et companie mais la je sais pas encore comment faire !!!
Une liste dans un fichier texte, mis a jour 1 fois par mois lors de la mise a jour de l'addon.
Un detection/modification automatique mais ca risque de poser des problemes.

**Comment by FreeFighter77** [comment]
Je reviens a la charge avec mon site de replay, http://pastebin.com/nVhBzBkF
Je suis bloqué ligne 140 j'aimerais que quand il y a direct dans enry1 il ne m affiche rien des 4 entry correspondantes,une ame charitable ?
Et egalement faire des sous genres,mais tjs pas trouvé comment style divertissement info ....

**Comment by TmpName** [comment]
Et il marche pas ton code ?
C'est quoi les 4 entry correspondante ?

**Comment by FreeFighter77** [comment]
tout le code marche,mais sur le site page 6 par exemple il rajoute des liens de tele direct (rtl9,tf1,ect)
donc ma pattern movie recupere bien tt,mais recupere aussi les image liens de c chaine,et donc je voulais faire en sorte que si il y a direct dans le titre (aentry1) il ne les affichent pas

**Comment by TmpName** [comment]
Manque pas la tabulation (indent) apres le else: ?

**Comment by FreeFighter77** [comment]
#if '[direct]' in aEntry[1]:
                #oGui.addMovie(SITE_IDENTIFIER, 'showMovies', sTitle, aEntry[0], aEntry[2], oOutputParameterHandler)

En faite oGui etc n est pas bon,je voudrais une commande pour dire que si il y a direct ne pas afficher, un truc du genre delete ou remove ....

**Comment by TmpName** [comment]
if not '[direct]' in aEntry[1]:
                oGui.addTV(SITE_IDENTIFIER, 'showHoster', sTitle, '', aEntry[0], aEntry[2], oOutputParameterHandler)

???

Sinon tu met dans le patter une exclusion, pour ne pas recuperer les liens avec 'direct'

**Comment by TmpName** [comment]
Mise a jour de mangacity, normalement il devrait etre fini

> http://pastebin.com/KwCBSPLA

Pour marcher utilise ce host

>
