### ISSUE TITLE
Avancement de vStream

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#29]
Tout d'abord Merci pour votre aide précieuse. voici ceux que j'aimerais par la suite votre aide et bien sur la bienvenue :)

Ralentir un peux l'arriver de catégorie déjà présente trop de fois genre films et accentuer sur ce qui ce fait plus rare exemple les animés les documentaires.

Amélirorer la recherche visuel pas mal de problème avec les caractère accentuer.Par la suite proposer peux être plusieurs site de recherche visuel.

Améliorer la fonction tv et pouvoir proposer directement c'est playlist m3u a l'addon.

Voila pour le gros du travail, encore merci et longue vie a vStream :)

**Comment by TmpName** [comment]
Alors je viens de me servir de la recherche visuelle pour la premiere fois (wé je sais mais j'en ai pas eu besoin) et je n'ai pas vu de probleme de caracteres speciaux, par contre j'ai cliqué sur "Titre du film - nom de l'episode (partie 1)" et evidement avec une nom pareil la recherche globale ne m'a trouvé q'un film : celui d'un vient le titre.

Mais a part un nettoyage du nom pr ameliorer la recherche pas vu de prb, il y a une semane j'ai corrigé 2 / 3 site a cause du %20 a la place du "+" ou vice versa, mais la pour des recherches en 2 mot j'ai eu un film trouvé sur tout les sites.
