### ISSUE TITLE
Retour mise a jour

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#30]
Alors, 
-fullstream.me manque un film sur 2 je publie la correction de suite.
-Dpstreaming.org erreur de script sur films nouveautés,je le fais refonctionner (ligne 285) avec:
sTitle = unicode(aEntry[2], 'utf-8')#converti en unicode
          #sTitle = unescape(str(sTitle))
            sTitle = sTitle.encode( "utf-8")
Je ne modifie pas car je sais pas si ca influe sur series ou mangas (j'ai regardé en vite fais ca n'a pas l'air

**Comment by TmpName** [comment]
Je met en ligne la correction pr dpstreming.org
Ca vient du film automata, il y a un accent sur le "o", a mon avis ca va donner l'occasion de tester les autres sites ^^.

**Comment by FreeFighter77** [comment]
J ai fais pas mal de test avant de corriger,ca frise sur quoi ?

**Comment by TmpName** [comment]
Va simplement dans "serie"
Il n'y a pas de qualitée pour les series, donc le regex recherche sans fin.

**Comment by FreeFighter77** [comment]
Yep exact autant pour moi,j ai test recherche films genre ... zappe serie mdr

**Comment by TmpName** [comment]
Bon j'ai rectifié le tir pour le 1 film / 2 mais je n'arrive pas a trouver pkoi j'avais viré les commentaires en cas de recherche.
Tout a l'air de fonctionner, affaire a suivre......

**Comment by FreeFighter77** [comment]
bien comme d'ab tres beau boulot,merci TmpName ;)

**Comment by LordVenom** [comment]
Salut pour dpstreaming y a un patern en trop dans les series, un print visible, et quand ont vas dans le hoster les accent sont encoder.

**Comment by TmpName** [comment]
Corrigé, et j'ai viré tout les caracteres accentué non utf-8 des titres.
