### ISSUE TITLE
Mangacity

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#31]
Bonjour, 

Cette source a quelque bug, le lien des catégorie en home anim nouveauter affiche l'ordre alphabétique.Il y a un print qui affiche du code dans kodi.xbmc dans le hoster.

Pk avoir supprimer le travail que j'avais effectuer dessus ?
Pk utiliser de la couleur rouge pour l'affichage alphabétique ?

**Comment by TmpName** [comment]
En fait, tu etais partir sur une vielle source, j'avais pas vu que tu avais fais des modif dessus. Mais ya pas de probleme, github memorise tout, je remerge tout dans la journéee.

J'ai pris le rouge au hazard, si tu preferes une autre couleur ..., y a aussi un orange je crois, en fait j'ai pris "corail" sans savoir a quoi cela correspondait comme couleur.

**Comment by TmpName** [comment]
Corrections effectué, tu peux y aller.

**Comment by LordVenom** [comment]
Re, tous n'est pas revenue comme je l'avais coder mais bon c'est pas bien grave.Je regarde ça des que j'ai le temps. Pour les couleurs il faut rester sur les même que les autres sources aucune pour les catégories.

**Comment by LordVenom** [comment]
Bonjour, anim genre n'affiche rien.

**Comment by TmpName** [comment]
Ben j'ai fais au mieux en comparant la 1er et 2 eme source, apres il y avait trop de modif.

J'ai corrigé le prb de genre, je sais pas pkoi mais depuis peu les liens sont code url, en passant je vire le host pixil car j'ai rajouté un host "lien_direct"

En fait Vstream va passer tout les hosts, et a la fin si il n'en trouve aucun, teste les lien directs, j'ai fait cette modif car j'ai trouvé un deuxieme lien direct sur leur site en plus de pixil, comme ca ils seront tous gerées, y compris ceux que je n'ai pas encore vu.
