### ISSUE TITLE
easywatch

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#32]
voila j'ai rajouté ce hoster (fullstream-me),mais comme mailru on peut changer la qualité,mais je n'arrive pas a l'integrer... ca se presente comme ca:
sources: [{file:"http://67.215.1.82/lkvyqm7ramksbyn55xb76qal7am6nrjut3racgtvrgswaffnb5zplqbaludq/v.mp4",label:"SD"},{file:"http://67.215.1.82/lkvyqm7ramksbyn55xb76qal7am6nrjut3racgtvr4zwaffnb5zmveiolvca/v.mp4",label:"HD"}]
Un bon parmi nous ?? ;)

**Comment by TmpName** [comment]
Hello, je te croyais mort depuis le temps ^^.

J ' y jete un oeuil de suite.

**Comment by FreeFighter77** [comment]
J'ai fais une petite pause,mais me revoila ^^
