### ISSUE TITLE
exashare

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#33]
alors il fonctionne sur des liens anciens,mais plus sur des recents ... chez urlresolver il semble l'avoir mis a jour,j'ai essayé de faire un portage mais ....
voila la difference entre 2 liens:
- file:
"http://n1c2.exashare.com:5777/tcx2cvkx3im56odwtyv6janu5tsrqo7or57vtzjqqjei7rcxacch2joed7ra/v.mpd", type: "video/dash",
-file: "http://vs25.exashare.com:8777/ecxkf53g3ym56odwtzzojcvxvjregm3okpb67sfhfiopy6eoxn4o36f2kkoa/v.mp4"

**Comment by TmpName** [comment]
Bon ben j'ai commencé mais je dois laisser tomber et URLResolver inclu dans kodi ne doit pas marcher non plus.
En fait Exashare propose maintenant le fichier en 2 parties, une pour l'image et une pour le son, et je n'ai pas trouvé comment faire gerer ca a kodi.

**Comment by FreeFighter77** [comment]
Je pense que kodi le fais,sur navix il y a des chaines tv ou tu as 2 flux audio(2 langues) pour 1 flux video.mais alors apres comment faire ...

**Comment by TmpName** [comment]
Ha ? j'ai pas vu, j'ai NaviX mais c'est tellement lent que m'en suis jamais servi, vais aller voir, mais pr le moment sur les forums de kodi, je vois que ce n'est pas encore pris en compte car ffmpeg (la librairie utilisé par kodi) ne le gere pas.

**Comment by FreeFighter77** [comment]
http://bit.do/4z6X

**Comment by FreeFighter77** [comment]
J'ai trouvé ca,mais vu que j'y connais rien ...
http://stackoverflow.com/questions/28219049/combining-an-audio-file-with-video-file-in-python

**Comment by TmpName** [comment]
Ben le truc c'est que la plupart des applis font ca apres avoir telecharger les fichiers, pas en direct/stream.
