### ISSUE TITLE
youwatch

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#34]
No comment ne demarre jamais ou rarement 
kodi log:
http://pastebin.com/sBevyD1z

**Comment by TmpName** [comment]
Pour lui c'est normal, teste sous firefox, les liens peuvent mettre facilement jusqu'a 1 minute pour demarrer, kodi lache l'affaire avant.
Une modification a tester c'est d'augmenter le timeout, mais du coup tu va perdre la main pendant une minute si on le regle comme ca. C'est a dire que kodi va bloquer pendant 60 secondes, c'est long et la touche "x" ne marchera pas (deja testé)
