### ISSUE TITLE
Dpstreamiz

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#35]
J'ai commencé ce site films ok,séries je n arrive pas a isoler le telechargement,ca pose pb pour les liens sous dlprotect en vostfr (ex:elementary)
http://pastebin.com/k8hjs7aK

**Comment by TmpName** [comment]
Attend je reconnais ce site, on l'a deja fait, et avec les liens dlprotect en plus, laisse moi 5mn

**Comment by FreeFighter77** [comment]
c un confrere de dpstreaming.org c'est pour ca,ca te parle ...

**Comment by TmpName** [comment]
Yep c'est ca ^^, mais je viens de regarder, c'est pas les memes liens.
Par contre la manip pour recuperer les liens dlprotect doit etre la meme.

**Comment by FreeFighter77** [comment]
EN faite tt et deja configurer il les recupere nickel,le probleme est que vu que je n arrive pas a isoler les liens de telechargements je fais ca:
sHtmlContent = sHtmlContent.replace('<a href="http://www.ddlprotect.com','')
Et donc ca annule egalement les liens de streaming ...

**Comment by TmpName** [comment]
Et sans remplacer ? Si ca marche sur dpstreaming ca doit marcher aussi sur celui la.

**Comment by FreeFighter77** [comment]
sans replace ca fonctionne oui,mais la pattern recupere des liens de telechargement en plus des liens de streaming

**Comment by TmpName** [comment]
Wé me souvient que le pattern de dpstreaming pique pas mal.
Fait un regex limite entre le mot "telechargement" et "streaming", sinon si tu galeres fait le en 2 fois
1 regex qui prend le code situé entre ces 2 mot.
1 regex pour recuperer les liens dans le precedent resultat.
De faire ca en deux fois accelere egalement le traitement.
