### ISSUE TITLE
netu

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#36]
et maintenant le tour de netu qui a pour les liens recent une autre adresse:
http://netu.tv/watch_video.php?v=AMAR6S958BOD
Et pour moi ce hoster coupe frequement en pleine lecture,de meme pour flashx (pour les 2 si j avance la lecture ca coupe)

**Comment by TmpName** [comment]
C'est normal pour netu, en fait ce n'est pas un fichier que tu lis mais une playlist composé de morceaux de fichiers, donc quand ca lague sur un morceau ca coupe (alors que le precedent etait ok), et tjours au meme endroit, mais le pire c'est quand il manque un bout de fichier, car tu ne le saura que en regardant le film. Et du coup impossible de telecharger le fichier et la marche rapide est a eviter.

Je regarderais pr la mise a jour plus tard si personne en s'en est occupé.

**Comment by TmpName** [comment]
C'est bon tu peux tester la nouvelle version, mis a jour sur sur beta.
