### ISSUE TITLE
Truc bizarre dans full_stream_me

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#38]
Question con, suis tombé sur ca hier
    oRequestHandler = cRequestHandler(sUrl)
    oRequestHandler.setRequestType(cRequestHandler.REQUEST_TYPE_POST)
    oRequestHandler.addParameters('login_name', 'vstream')
    oRequestHandler.addParameters('login_password', 'vstream')
    oRequestHandler.addParameters('Submit', '')
    oRequestHandler.addParameters('login', 'submit')
    sHtmlContent = oRequestHandler.request();

Dans showhoster, je laisse, ou je peux virer ? Doit y avoir pas mal de monde se connectant avec le pseudo vstream sur ce site ^^.

**Comment by LordVenom** [comment]
Je sais plus sur quel site j'avais besoin de ça pour afficher les films de bonne qualiter. A voir si y a toujours besoin. Peux importe le nombre de connection pour ce login.

**Comment by TmpName** [comment]
Bon j'ai testé, j'ai pas vu de differences, je met en commentaire pr le moment.
