### ISSUE TITLE
Mise a jour retarder

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#41]
Bonjour, pour le moment l'addon ne repond pas asser bien pour une mise a jour. Je sais pas pk mais je le trouve lent en ce moment faut que je plonge la dedans.

Dans les préférences de l'addon dans plugin on/off j'ai noter les sites que je trouve lent.
Par la suite un code couleur pour signaler les meilleurs sites serais peux etre une bonne idée.

**Comment by TmpName** [comment]
Oui, et j'ai pensé a la meme chose pour les hosts.
Par contre je viens de tester dpstreaming.org et je n'ai pas eu de probleme de lenteur, meme pas 1 s pour l'affichage et j'utilise une petite machine 100/100 passive.
