### ISSUE TITLE
IPTV

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#44]
TF1 a disparu
une url qui marche chez moi, je sais pas si elle est publique ou reservé mais pour une adresse, ils ne devraient pas nous le reprocher.

h tt p://medias.streaming-hub.com:8090/hls/tf1.m3u8

Sinon, a voir si libretv.me nous permettent de scrapper leurs listes, si tu gardes leur nom ?  y a de quoi faire un addon d 'iptv terrible via leur site mais vu la guerre qu'il y a entre les "publicateurs d'adresses IPTV" vaut mieux eviter de se les mettre sur le dos.

**Comment by LordVenom** [comment]
Faudras que je test ça, 

Perso je vais ici 
http://www.tvonlinestreams.com/category/c22-french/
problème les liens ne tienne jamais trés longtemps et donc inutile de tous mettre.

**Comment by TmpName** [comment]
Ben en fait c'est pour ca que libretv.me vaut le coup, c'est un projet collaboratif, il y a plusieurs personnes qui gerent plusieurs listes, donc c'est assez regulierement mit a jour. Il y a deja un addon qui recupere leur liste, mais payant, apres c'est des listes publiques, n'importe qui peut s'en servir pour lui meme.

Mais vu le cote communautaire, on ne peux pas recuperer leurs liens sans leur permission.

**Comment by LordVenom** [comment]
Voila c'est demander ont peux l'utiliser dans tv la ou y a free tv, tv web, je vais faire une section libretv.me. Logiquement le code pour recupere un m3u et deja fait, mais oui ça surement un moyen de custom.

**Comment by LordVenom** [comment]
J'ai commencer mais y a encore pas mal de bug, j'utilise un code pour lire le m3u histoire d'être sur que tous ceux qui peuvent installer vStream peuvent lire le contenu.La suite stabiliser le code, voir pour les programme tv.

**Comment by TmpName** [comment]
Je viens de faire un rapide test, j'ai pas vu de soucis, pour cette partie je pense que tu peux la laisser dans la mise a jour, peu de chance d'avoir des bugs et tu aura deja quelques retours, par contre la version customisee ne sera jamais finie pour la mise a jour, en tout cas pas par moi (je cherche des idees pour faire ca)

Au moins faire une liste de favoris, et quelques icones.

**Comment by LordVenom** [comment]
Oui ça fonctionne, ont verras bien ont n'est pas au pieces lol

**Comment by TmpName** [comment]
J'ai une question, chez moi il n'y a aucune restriction d'accés donc je ne suis pas sur.

Le m3u est assez long a obtenir, donc histoire d'eviter d'avoir a le retelecharger 10 fois lors des promenade dans les menus, je compte le telecharger une bonne fois pour toute quelque part avec comme nom la date du jour des que la personne va dans libretv, et me reservir de celui la jusqu'au lendemain. Plus rapide pour nous, moins lourd pour leur serveur.

Ma question c'est ou tu le mettrais ? Il y a un repertoire temporaire commun a tout les addons sur kodi ? je crééun repertoire juste pour Vstream ?  J'utilise le repertoire temporaire de l'OS ?

**Comment by LordVenom** [comment]
Y a un cache special pour les addons pour mettre les bases de donners par exemple tu verras le code dans config.py

exemple
self.__sFileDB = os.path.join(self.__oCache,'vstream.db')
