### ISSUE TITLE
le béta

### ISSUE THREAD

**Issue by poto25** [LordVenom/venom-xbmc-addons-beta#50]
Bonjour j'ai un soucis quand je télécharge la béta et puis je l'installe depuis kodi j'ai un message ,
j'ai(  structure de l'extension incorrect ) c'est bizare pourtant j'ai bien suivi la procédure merci de me répondre et merci d'avance.

**Comment by LordVenom** [comment]
Bonjour, La bêta et faite pour les developpers uniquement.dsl mais si ont fait du support pour les 2 version ont vas pas s'en sortir.

@+

**Comment by poto25** [comment]
Salut  LordVenom et merci pour ta réponse c'était juste pour avoir poypi , c'est quand la prochaine mise a jour de vstream merci de me répondre et bravo pour votre plugin

**Comment by LordVenom** [comment]
Pour le moment aucune idée fin du mois si tous vas bien.

**Comment by poto25** [comment]
Ok merci beaucoup pour votre travail
