### ISSUE TITLE
AttributeError: 'str' object has no attribute 'getValue' 

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#52]
Bon la je galere

Si je passe par la fonction addNone(), je trouve dedans self.addFolder(oGuiElement, '') 
Fonction declarée  def addFolder(self, oGuiElement, oOutputParameterHandler='', isFolder=True):

Et du coup je me retrouve avec ce message d'erreur car oOutputParameterHandler est devenu une simple string et n'a pas de fonction getValue.

J'ai bien trouve une solution avec try: et execpt: mais je suis pas sur que ce soit la methode la plus clean. Comme declarer correctement la fonction addFolder

Edit: autre probleme oOutputParameterHandler.addParameter('sFav', sFunction)
quand il n'y a pas de fonction sFav se retrouve vide

sItemUrl est bien = sFav=&blabla=blabla

Mais apres le clic de selection il devient sFav&blabla=blabla >> crash de la fonction __init__  dans cInputParameterHandler (vu qu'on utilise le = pour splitter.

Il ya la possiblité facile de ne pas utilser sFav, plus de bug mais le probleme reste.

**Comment by LordVenom** [comment]
def addNone(self, sId): 
        oGuiElement = cGuiElement()
        oGuiElement.setSiteName(sId)
        oGuiElement.setFunction('load')
        oGuiElement.setTitle('[COLOR= red]'+cConfig().getlanguage(30204)+'[/COLOR]')
        oGuiElement.setIcon('none.png')
        oGuiElement.setMeta(0)
        
        oOutputParameterHandler = cOutputParameterHandler()
        oOutputParameterHandler.addParameter('siteUrl', 'none')
        
        self.addFolder(oGuiElement, oOutputParameterHandler)

Pour éviter de faire planter l'addon mais il affiche plus le message faut que je regarde, si tu trouve corrige sinon je le ferais + tard.

**Comment by LordVenom** [comment]
Pour moi il suffi de faire : 

    def addNone(self, sId): 
        oGuiElement = cGuiElement()
        oGuiElement.setSiteName(sId)
        oGuiElement.setFunction('load')
        oGuiElement.setTitle('[COLOR= red]'+cConfig().getlanguage(30204)+'[/COLOR]')
        oGuiElement.setIcon('none.png')
        oGuiElement.setMeta(0)
        
        oOutputParameterHandler = cOutputParameterHandler()
        #oOutputParameterHandler.addParameter('siteUrl', 'none')
        
        self.addFolder(oGuiElement, oOutputParameterHandler)

et de changer

    if (aResult[0] == False):
        oGui.addNone(SITE_IDENTIFIER)
        return False

en 

    if (aResult[0] == False):
        oGui.addNone(SITE_IDENTIFIER)

**Comment by TmpName** [comment]
Ben en fait j'essaye de ne pas trop modifier le code "racine".

Mes problemes ont commencé quand j'ai eu besoin de faire une fonction add.XXX qui afficherait un texte mais non cliquable. Pour le moment on fait
>> oGui.addDir(SITE_IDENTIFIER, 'load', '[COLOR khaki]Tu veux voir ta chaîne sur Libretv.me alors partage ta chaîne![/COLOR]', 'tv.png', oOutputParameterHandler)

Et ca recharge la page si on clique dessus, pour le moment c'etait pas trop genant, mais avec les m3u si tu te rate c'est 4/5 s de chargement.

Et si on ne met pas de fonction ca utilise la fonction 'load' par defaut ou ca crashe dans certains cas.

Donc vais bidouiller un truc que je te laisserait fusionner si tu valides. La j'en ai encore pour 1/2 jours je pense.

**Comment by LordVenom** [comment]
J'ai hate de voir ça un lien non cliquable j'ai pas d'idée a part peux etre un force return.

**Comment by TmpName** [comment]
Yep, c'est juste ca.
Bon en fait j'ai du merder, ca a tout validé direct, mais y a juste 3 lignes a virer si ca te va pas.

Nouvelle fonction 
>> oGui.addText(SITE_IDENTIFIER, sTitle, oOutputParameterHandler)

oOutputParameterHandler ne sert a rien mais je l'ai laissé au cas ou ....

**Comment by LordVenom** [comment]
Ok pas de soucis a premieres vue ca fonctionne bien. je cherche un api tv mais pour le moment nada.

**Comment by TmpName** [comment]
un api TV ?

**Comment by LordVenom** [comment]
Oui au lieux d'utiliser un xmltv mais j'ai pas trouver en france.

**Comment by TmpName** [comment]
Ha ok je comprend, perso j'ai deja testé 2 xmltv (les plus connu) ca m'a pas emballé.
