### ISSUE TITLE
Epg

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#54]
A voir si ont peux pas faire quelque chose avec ça.

http://www.webgrabplus.com/epg-channels

**Comment by TmpName** [comment]
J'ai jeté un oeuil rapide, dans le fichier ini on peut trouver tout les lien et pattern pour recuperer les infos mais comment tu veux presenter ca dans Vstream ?

**Comment by LordVenom** [comment]
J'ai pas d'idée encore mais y a de quoi faire un sacré Epg aprés est ce que vStream en a vraiment besoin surement pas pour toute les langues.

**Comment by TmpName** [comment]
Ben d'avoir un programme TV ca peut servir, mais j'arrive pas a avoir comment le gerer.
En menu contextuel ca ne va pas etre ergonomique, et autrement il me faut partir de zero car jamais fait.
J'ai un addon (non fonctionnel) appellé "TV guide" qui affiche une grille de programme sans perturber l'epg reglé de base a Kodi, c'est a dire que c'est un addon qui affiche sa propre grille EPG, a voir si on voir comment il fonctionne ou rajouter un fichier xml valide.

**Comment by LordVenom** [comment]
on peux toujours utiliser la popup sur le coter comme pour afficher le log.mais je connais pas trop c'est limite. Aprés il faudrais réussir a utiliser les fichier dans le zip et laisse le choix au utilisateur d'installer ou non certain guide.

**Comment by TmpName** [comment]
ben en fait c'est pas le fichier dans le zip que je trouve utile, il ya un fichier ini directement acessible sans passer par le zip, contenant assez d'infos pour generer un fichier xml par exemple.

http://www.webgrabplus.com/sites/default/files/download/ini/info/SiteIni.Pack/France/canalsat.fr.ini

**Comment by LordVenom** [comment]
Oui, j'avais vue ce ini, et ce xml en question la popup ne la prend pas en charge ?

**Comment by TmpName** [comment]
Ben la je t'avous, suis a la ramasse complet, je vois meme pas ce qu'est le popup de coté, ni comment l'utiliser ...

**Comment by LordVenom** [comment]
Oui j'ai fait des test aussi, ça fait trop de taff, je vais cherche encore pour trouver quelque chose de bien.

**Comment by TmpName** [comment]
Bon j'ai testé ton code, ca m'affiche bien une fentre sur le cote, un peu trop grosse meme je pense, et dedans on doit pouvoir y ecrire ce que l on veut.

Mais quoi ?

On peut faire une recherche, par rapport au lien selectionné, pour voir ce qui passe en ce moment, ou juste apres ?
Limiite on doit pouvoir scrapper ces infos d'un programme tv en ligne

Ps: il y a egalement la version html avec images.
http://www.mycanal.fr/guide/maintenant/tous/?page=3

**Comment by LordVenom** [comment]
Dans mon idée on click droit sur Tf1 et Epg puis on a la popup avec le programme du jour de Tf1.Donc oui il suffi de le prendre sur un programme tv online.Reste a trouvé le bon site pour les infos, je cherche encore.

**Comment by TmpName** [comment]
Celui de yahoo est pas mal  https://programme.tv.yahoo.net/php/grille/index.php
Le lien ne marchera pas car il marche en post, mais jette un oeuil
Tu peux specifier 1 chaine et une plage de 4 heure pour obtenir un resume de 4/5 ligne, mais avec le resume de l'emmission coupe.

**Comment by LordVenom** [comment]
Je suis partis sur celui la http://television.telerama.fr/tele/chaine-tv/tf1,192.php

**Comment by LordVenom** [comment]
Bon j'avance doucement mais surement.J'ai fait une class et quelque test reste a faire correctement la patern et a trouver comment faire pour voir quel chaine c'est.

**Comment by TmpName** [comment]
Arf, courageux, moi j'aurais pris plus simple ^^ (la version pr feneant).
