### ISSUE TITLE
module resolver

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#55]
J'ai tenter de mettre l'addon resolver sans succes j'ai un probleme d'import ou je bloque, il importe bien mais c'est pas les bonne variable qui a dans l'import.J'ai laisser le code en commenter dans lib/gui/hoster,  le problème d'import et dans hosters/resolver.py

**Comment by TmpName** [comment]
Je croyais que tu ne voulais pas utiliser ce pluggin pour garder Vstream autonome?
Il peut servir si on rajoute de nouveau host payant mais sinon suis pas sur de son utilité.
Il n'est jamais a jour et l'equipe qui le gere n'est pas tres reactive.
Meme avec 1 seule mise a jour par mois je suis sur qu'on aura moins de probleme sans eux.

**Comment by LordVenom** [comment]
Je suis tous a fait d'accord avec toi, c'est pourquoi l'utilisation de resolver ce fait en dernier recours.
Mais bon pour le moment le problème et regler ça ne fonctionne pas.

**Comment by TmpName** [comment]
Bon j'ai fait des tests, ca marche chez moi, je te l'ai laissé en desactivé.

Mais je confiirme, c'est de la merde, impossible de voir un lien youtube de docspot car :
1 - le lien commence par //
2 - https est trop different de http pour le resolver
3 - lien special ressemblant a www.youtube-nocookie.com qui n'est pas géré par un des addon les plus utilisé, fourni a la base par defaut.

Cet addon est un gag.
