### ISSUE TITLE
Nouveau site tv_streaming_ch

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#56]
cf https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/tv_streaming_ch.py

Gere film/serie/anime/documentaire
VF/VOSTFR
Emissions TV/TV realitées mais par contre marche a part. Impossible de faire comme pour manga ou anime.
Je sais pas si je suis comprehensible ? Quand on passe par MOVIE_NEWS le site apparait quand on choisit "film nouveauté" sur la page d'acceuil mais il n'y en a pas pour les TV realité.

A pas mal d'exclu comme la vielle serie DA "SOS fantome"

Par contre 1 seul host a chaque fois.

**Comment by arzaz** [comment]
Bonjour TmpName,

A chaque fois que je lance une video j'ai l'erreur echec vstream?

**Comment by LordVenom** [comment]
Si il te manque des catégorie crée les ou dit moi celle que tu veut.

**Comment by TmpName** [comment]
@arzaz le host serais pas uptostream (limite en utilisation) ?
Tu as aussi ce probleme @LordVenom ?

Pour la categorie a rajouter, je m'en occupe (vu que tu as deja commencé), ce sera un truc du style REPLAYTV.

**Comment by LordVenom** [comment]
Perso j'ai echec de lecture mais c'est due a la limite d'upto
