### ISSUE TITLE
Besoin de testeur.

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#59]
Bon je commence a peter un cable
Quelqu'un peut me tester cette source pour un site
http://pastebin.com/PjyzZqwz

De memoire "Film nouveaute" ne marche pas il faut aller a "tout les films".

Juste me dire si quelqu'un arrive a lancer une video, merci.

Si ca rate merci de me laisser la version de kodi et l'OS.

**Comment by LordVenom** [comment]
Oui ça tourne pour moi , j'ai testé Road47 et Kundo, effectivement Film nouveauter et vide.

**Comment by TmpName** [comment]
Ok merci, suis rassuré.
