### ISSUE TITLE
Fonction Goto Page #

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons-beta#62]
Bonjour
est ce que on peut ajouté cette fonction 'goto' pour choisire une page avec le clavier numeric
j'ai trouvé un addon qui a cette fonction ai j'ai le code pour ça 

http://pastebin.com/egaaFvCe

    from core import AddonCore
    from xbmcdict import XBMCDict
    from BeautifulSoup import BeautifulSoup, SoupStrainer, Comment
    from favorites import ContextMenu as Fc

AddonCore
core.py
http://pastebin.com/3eDayxzb
database.py
http://pastebin.com/W4Ga98PS
favorites.py
http://pastebin.com/29psi7yt
xbmcdict.py
http://pastebin.com/vksMG2Gx
seting.xml language
http://pastebin.com/GLuMB3PD

pour testé sur film-streaming.co 
http://pastebin.com/3FQFLeNR

**Comment by LordVenom** [comment]
Bonjour, ça ne vas pas fonctionner sur tous les supports.Ont peux faire une fonction dans le genre mais direct dans l'addon des que je suis moin oqp je regarde ça.
