### ISSUE TITLE
Tntv.rattrapage

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#63]
Bonjour , juste pour signaler tntv a une erreur de script lorsque l on clique sur un lien ... Je viens de m en apercevoir a l'instant ...

**Comment by FreeFighter77** [comment]
PS: J ai bien evidemment regardé, mais je ne sais pas du tt d ou ca vient ....

**Comment by TmpName** [comment]
Je croyais que tu l'avais corrigé, moi j'ai pas de probleme quand je teste.

**Comment by FreeFighter77** [comment]
J ai corrigé l onglet next qui n apparaissais pas dans les catégories .
Le reste ne vois pas du tt d ou ça viens, au passage très beau boulot pour cette source, j ai tjs essayé de faire les catégories jamais réussi ...
Voici le log kodi : http://pastebin.com/S28Rs6WP

**Comment by TmpName** [comment]
Bon ben j'ai testé "chasseur d'appart du 08/07/15 sur youwatch, pas de problemes, moi ca a marché.
Sinon j'ai deja vu ce bug sur mino60 je crois.
Il y a moyen de coriger ce probleme mais je pense que ca vient du systeme ou des versions des appli.

la chaine doit ressembler a
lienblaba&a=4&b=5&c=&d=8
alors que toi tu as
lienblaba&a=4&b=5&c&d=8

Le bug est sur thumbnail

et le parser fait par rapport au = et & du coup ca crash.

J'ai deja eu ce bug, je n'ai jamais pu le corriger, je l'ai juste contourné, c'est a marquer en bug.

**Comment by TmpName** [comment]
Bon la me faudrait l'avis de Venom
Pour moi le probleme vient de la version de urllib
On fait 
>>    def getParameterAsUri(self):
>>            if len(self.__aParams) > 0:
>>                    return urllib.urlencode(self.__aParams)
>>            return 'params=0'

Et je pense que c'est a ce moment ou si on a un parametre nul selon la version on se retrouve avec dans le lien 'param' au lieu de 'param='.

Soit on laisse tomber, et risque de provoquer des bugs sur vielle version

Soit on fait un patch pas tres performant sur le fichier inputparameterhandler.py fonction init. Le code est actuellement tres optimisé et la correction va etre moche.
Un test de plus via regex par exemple pour rajouter des "=" aux parametres manquants.

**Comment by LordVenom** [comment]
Perso j'avais un lien qui planter télérealiter/le mag l'ile des veriter/ 13/11/14 vodlocker problème résolut 

cHosterGui().showHoster(oGui, oHoster, sHosterUrl, '') 

en 

cHosterGui().showHoster(oGui, oHoster, sHosterUrl, sThumbnail)

Mais il devrais pas planter même sans variable je regarde ça.

**Comment by LordVenom** [comment]
Bon vue toute les modifs que j'ai fait c'est dernier temps je me suis un peux perdu, sThumbnail sur le hoster n'est plus nécessaire puisque le code vas récupéré les infos de l'ancien label mais dans la pratique j'ai pas encore bien modifier. j'ai donc virer les appelles a sThumbnail dans le hosters et forcer un sThumbnail de base ou cas ou.

**Comment by TmpName** [comment]
Ben en fait c'est justement mon probleme, soit un fait en sorte que jamais une fonction passe '' en parametre, ce qui arrive de maniere aleatoire car le meme code marche chez moi et pas FreeFighter77, soit on modifi le code pour qu'il puisse corriger ce defaut mais en perdant en optimisation.

**Comment by LordVenom** [comment]
Logiquement le param ne doit pas être vide si il et vide c'est une erreur de code.Donc ont touche pas si une erreur et remonter c'est qu'ont a oublier un truc.

**Comment by FreeFighter77** [comment]
Venom je viens de tester a l'instant et c'est bon le probleme a disparu ... Merci pour tout le boulot que vous faites : TmpName,Mino et toi ;)

**Comment by LordVenom** [comment]
problème des icones corriger merci j'avais même pas vue.
