### ISSUE TITLE
Choisir page

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#64]
Bon j'ouvre un nouveau post ici vu la longueur de l'ancien.

J'ai fait un copier/coller du code de Venom et now ca marche, mais c'est pas tres beau a voir.

http://pastebin.com/jHZBfzD6

**Comment by LordVenom** [comment]
A priori il faut juste virer le replace 

http://kodi.wiki/view/List_of_built-in_functions

XBMC.Container.Update(%s, replace)

le replace efface l'historique de click, je pense qu'il faux le garder.
Sinon bon taff je vais regarder quand même si ont peux pas passer par une function déjà créer mais il me semble que ça seras le seul choix.

**Comment by LordVenom** [comment]
Alors j'ai fait une function gui.selectpage j'ai modifier le nom de celle que tu avais créer pour pas effacer ton travail.
Ont pers la vérification de num page max mais elle s'implante toute seul et devrais fonctionner partout a vérifier si le parse getNumberFromString() retour toujours le bon chiffre.
