### ISSUE TITLE
Dpstreaming.org

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#65]
Juste pour signaler que dans Télévision Replay, il y a certains endroit vide (kohlanta,qui est la taupe ...) J y orais bien remedié,mais vu la complexite des patterns,peur de faire une betise.
kohlanta ex:  http://pastebin.com/FJJQ2QUu

**Comment by TmpName** [comment]
Il me faudrait le site, pour le moment j'ai toujours pas trouvé quel site deconne.

**Comment by LordVenom** [comment]
j'ai corriger, quand les sites n'ont pas série ou saison dans l'url mais qu'il sont quand même placer en séries ça deconne. Ce site c'est l'enfer j'ai contourner comme j'ai pus.

**Comment by TmpName** [comment]
Ha wi lol, me souviens j'avais eu le meme probleme pour les series n'ayant qu'un episode, ou les animés n'ayant qu'un seul OAV, c'etait classé comme des serie mais avec une gestion de film seul ^^.
