### ISSUE TITLE
Mise a jour auto

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#66]
Je voudrais votre avis, bonne idée, inutile ???

Je suis entrain de faire un system de mise a jour auto, en gros ça check les md5 des fichiers si c'est pas les mêmes il télécharger le fichier. Ce system seras limiter au source déjas existante je trouve ça dommage d'avoir autant de réactiver et de laisser trainer 1 mois et faire des micro mise a jour ç'est pas terrible.

**Comment by TmpName** [comment]
Moi je suis d'accord, il y a eu la mise a jour hier, et j'ai deja 3 sources qui deconnes, ca bouge tres vite.
Probleme, si l'user modifi lui meme la source, ou a sa propre modif perso, ca va lui virer ses modifs ?

Personnellement j'ai quelques modifs que je fais regulierement a chaque mise a jour.

**Comment by LordVenom** [comment]
Un boutton dans les paramètres permettra de lancer la mise a jour, pas de check auto trop lourd pour github je pense. Effectivement ont peux limiter mais des foix ont fait plus d'une modif par jour.

**Comment by TmpName** [comment]
Ha oui un boutton pour lancer une verification, c'est pas lourd ca.

**Comment by LordVenom** [comment]
Voila un debut de code, test et récupère les fichiers site du github "officiel". Je fait encore quelque mise au point et je fait une mise à jour pour tous le monde après y auras plus cas mettre les fichiers corriger sur le github "officiel" pour que les utilisateurs puisse faire leur mise a jour.

**Comment by TmpName** [comment]
Au niveau des droits d'acces, ca va donner quoi ?
Moi je m'en fou, j'ai tout les droits, mais certain de mes codes n'ont pas marché a cause des droits definis par le systeme lui meme.

**Comment by LordVenom** [comment]
Je sais pas trop ont verras bien les retours.J'ai utiliser xbmcvfs.File plutôt que open en espérant que ça ne bloque pas.Au pire ça afficher une erreur rien de bien grave.

**Comment by LordVenom** [comment]
Voila même sans droit admin ça a l'air de fonctionne sous windows, je test sous openelect plus tard.J'ai modifier les pref de l'addon y a un bouton beta testeur qui chargera les fichiers de la bêta au lieux de ceux de l'addon "officel" pratique pour nous, oublier pas ça charge que les sources.

**Comment by TmpName** [comment]
Ben c'est nickel, c'est le fichier qui change le plus souvent, et qui risque pas de faire planter tout Vstream en cas d'erreur sur le fichier, au pire l'user perd un site, on touche pas au coeur.

**Comment by LordVenom** [comment]
J'ai virer l'option bêta testeur, ça vas tous mélanger, je préfère rester carrer.
Maintenant le plus drole avec l'api github on peux savoir a quel date a etait effectuer le dernier commit et même qu’est-ce qui à était modifié. Exemple:

https://api.github.com/repos/LordVenom/venom-xbmc-addons/commits/master

Avec ça ont pourrais faire une mise a jour auto a partir des info de l'api mais je pense reste sur mes test md5 moins compliquer. Par contre je sais pas encore comment mais je doit pouvoir limiter le scan des 32 sources, si aucune modif depuis la dernier mise a jour, une date en paramètre masque devrais allais. Enfin tous ça pour dire que ça vas prendre un peux plus de temp.

**Comment by TmpName** [comment]
Je vois pas trop comment faire avec les dates, car sur Vstream, la date du fichier est celle de la mise a jour.
A defaut de faire avec le md5, utiliser la taille, c'est assez rare qu'une modif ne chnage pas la taille du fichier ?

**Comment by LordVenom** [comment]
Voila j'ai tout refait.

Test toutes les 10h. Si y a une mise a jour, il affiche un nouveaux raccourcis vers les preferences.

Note: si vous avez la bêta ne faite pas la mise a jour avec ce system ça charge les fichiers du repo officiel.

**Comment by TmpName** [comment]
Suis pas sur que le test toute les 10h soit necessaire, L'user se rend compte qu'un site deconne et clique sur le boutton si necessaire.
Ou alors un test toute les 48h c'est amplement suffisant, faut deja le temps de corriger le bug.

**Comment by LordVenom** [comment]
bon y a toujours un bug , je suis nul avec les dates je corrige ça bientôt.

**Comment by TmpName** [comment]
Lol, moi j'ai pas encore testé, j'attend la mise a jour ^^.

**Comment by FreeFighter77** [comment]
Petite question comment cela marche t il ?? A chaque fois que je clique dessus il me renvoye au menu de configuration ...

**Comment by TmpName** [comment]
Oui, je pense que c'est fait expres pour le moment car pas fini ou pour eviter les abus.
Une fois dans le menu, va au dernier onglet "outils" puis la tu selectionnes "mise a jour"
