### ISSUE TITLE
cJsUnpacker

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#67]
Salut, @TmpName tu sais faire marcher cette librairie?, je sèche pour le host letwatch.us

**Comment by TmpName** [comment]
Nope, jamais essayé mais j'ai regardé vite fait des resolver deja fait pour ce host et j'en ai trouvé utilisant demjson ou jsunpack, le premier ayant l'air plus lege, mais a inclure du coup car il n'y est pas par defaut, le second doit etre "livré" avec urlresolver vu que c'est leur source que j'ai vu.

**Comment by LordVenom** [comment]
Ok c'est résolut la lib inclus dans l'addon ne fonctionner pas, une nouvelle lib et un nouveaux host bientôt sur le bêta.
