### ISSUE TITLE
Letwatch

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#68]
Je viens de faire le test avec le hoster Letwatch, mais j'ai toujours l'erreur echec de la lecture.....

**Comment by LordVenom** [comment]
Hum, quel site quel film ? fonctionne t'il en web ou pas ? quel erreur retourne l'addon?

**Comment by arzaz** [comment]
Bonjour LordVenom,
Site--> Film Ilimit --> Film Underworld ere ultron

**Comment by LordVenom** [comment]
Faudras que je regarde quand je serais sur le pc mais dans mes souvenir c est mort sur le site.
