### ISSUE TITLE
Nouveau menu

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#73]
J'avais en tete de rajouter des menus, pkoi ?
Il y a Serie nouveauté, mais pas serie tout court, ce qui fait que la personne pour avoir la liste des serie du site X doit aller dans toutes les sources.
Je pensais rajouter "Films" "Series" "Animes" tout simplement, ou il y aurait la possibilité de voir la liste complete, surtout que dans certains site quand on choisit "nouveauté" c'est justement la liste complete que l'on obtient.

Creation egalement de menu comme FILM_A-Z, SERIE_GENRE, ....

**Comment by LordVenom** [comment]
Oui j'ai vue ça, les nouveautés sont souvent aussi la liste des films sur les sites. j'ai modifier les animes y a pas longtemps mais il faut vérifier chaque lien nouveauté car certain ont seulement 1 page .

Faut juste vérifier que ça fait pas doublon au pire virer nouveautés.Bref comme dab tu as carte blanche 

Note: mise a jour ce vendredi.

Note2: j'ai creer un menu context recherche similaire uniquement pour les films pour le moment l'idée c'est que si aucune source ne fonctionne pour un film on revient sur le films un coup de recherche similaire et il cherche sur toute les sources le nom du film.

**Comment by TmpName** [comment]
Le menu contextuel, on ma fait la remarque y a juste quelques jours justement.

Sachant que je garde les anciens "menu" pour eviter les problemes (pas besoin de corriger toute les sources, les modifs se feront petit a petit, de toute facon les 2 seront sur la page Home),  je rajoute :

ANIM_NEWS qui va remplacer ANIM_ANIMS

ANIM_ANIMS va devenir liste animés tout court (le vrac quand il y a pas moyen de faire plus propre) c'est le seul qui sera sur absolument toute les sources, mais pas nouveautées

ANIM_A-Z n'y sera pas car si le site propose la recherche alphabetique ANIM_ANIMS va devenir une recherche alphabetique, Ben oui pkoi faire une liste en vrac si il y a possbiité de faire une liste alphabetique propre.

MOVIE_MOVIE pour la liste de film vrac (ou alphabetique) mais pas nouveautées.

ANIM_GENRES, no comment

REPLAYTV_NEWS no comment

SERIE_NEWS meme punition que pr les films avec modif future de SERIE_SERIES

SERIE_GENRE (a voir, je sais pas si un site propose ca)

(A suivre)

**Comment by LordVenom** [comment]
Ben si c'est possible clique sur history sur un fichier 

https://github.com/LordVenom/venom-xbmc-addons-beta/commits/master/plugin.video.vstream/resources/lib/home.py

Aprés tu trouve la version que tu veut tu clique sur raw tu télécharge et op :)

**Comment by TmpName** [comment]
Ca y est merci, ca marche.

Bon j'essaye d'avancer mais en passant je teste tout les sources une par une, et je trouve pas mal de problemes comme films_ws qui decalle les film et plante aux series, donc ca risque de prendre du temps, pas sur de finir pour la mise a jour, mais dans tout les cas si ce n'est pas dans un menu ce sera dans un autre. Apres pour le paufinage .....

**Comment by TmpName** [comment]
Question !
J'ai le site Hd-stream.co, ca doit etre une source commencé pas finie, ca en est ou ?, elle marche presque chez moi, c'est passé a la trappe ?

**Comment by LordVenom** [comment]
Alors la oui pas vue passer la preuve c'est pas dans le settings.xml

- j'aurais mis le lien en bas 
nouveauter
plus vue
ect
toutes les sources. avec l'image hosts.png

**Comment by TmpName** [comment]
je vais voir si je peux reparer ces deux sources, mais a mon avis c'est encore des sources commencée jamais finie.

Pour le coté esthetique/ergonomique, je te laisse faire (a mon avis tu vas vouloir utiliser l'icone listes.png et chnager l'appellation "Tout" , ca veut rien dire mais je sais pas comment l'apeller. Jai vu aussi que now tu utilises vf.png et vostrf.png, mais trop tard, pas eu le reflexe non plus en modifiant les sources.

Pour le moment je me speede pour que tout refonctionne pour avant la fin de la semaine, dans la plupart des cas, c'est juste une ligne a rajouter pour faire apparaitre la source au plus d'endroit possible, et apres petit a petit j'arrangerais le truc. En fait dans la plupart des cas je rajoute une liste complete mais par ordre alphabetique quand je peux, plus gerable.

**Comment by LordVenom** [comment]
Une fois les raccourcis créer rien ne presse pour les remplir. Si il faut repousser la mise a jour ont le feras, prend ton temps vstream n'est pas une source de stress au contraire :)

**Comment by TmpName** [comment]
Bon c'est bon je pense avoir fini de toucher au coeur de Vstream, je te laisse la main pour reparer le theme que j'ai foutu en l'air ^^. Normallement plus de modifs de mon cote.

Tout devrait marcher comme avant, meme mieux pour certaines sources, mais comme j'ai foutu pas mal de bordel .....

Et j'ai commencé les listes alphabetiques (fullstreamme ok)

**Comment by LordVenom** [comment]
Voila je pense avoir fixer toutes les images et titre. je pense qu'avec le temps tu as retoucher tout les fichiers de l'addon :+1:
