### ISSUE TITLE
Timeout.

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#74]
Je suis a la recherche d'infos sur le timeout, en fait certain host on besoin de beacoup de temps pour donner le fichier (eg : youwatch), il y a la possibilité d'augmenter le timeout dans kodi mais probleme, si on met un timeout de 1 mn, Vstream sera bloque pendant 1mn, si je presse la touche X, ca arrette le telechargement mais kodi freeze jusqu'a la fin du temps.

Puis j'ai vu ce code qui pas de bol n'est pas celui utilisé
>>        xbmcPlayer.play(oPlayList)
        timer = int(cConfig().getSetting('param_timeout'))
        xbmc.sleep(timer)

Me suis dit "cool c'est ce timer qui fou la merde", pas de bol, on passe meme pas par lui.

Puis j'ai vu que apparement on passe par xbmcplugin.setResolvedUrl(sPluginHandle, True, item) et la j'ai laissé tomber....

Quelqu'un aurait une astuce, une manip dans kodi pour eviter le freeze, un code a modifier ...?

**Comment by LordVenom** [comment]
Il faut jumeler le timeout a un popup cancel bizarrement tu fait x ça plante mais pas si tu cancel un popup.C'est pourqoi j'ai ajouter

if dialog.iscanceled():
                break

dans les sites.

**Comment by TmpName** [comment]
Nope, en fait pas de probleme cote Vstream, meme pendant le decodage, la ca marche, c'est une fois le decodage effectué quand le player recupere le lien, eg pour le fameux youwatch, le lien est decode en 2s mais ca peut prendre 1mn pour avoir le film.

Edit:
Je suis en train de me demander si ca ne vient pas de Vstream finallement, je suis en train de tester des lien youwatch decodés avec l'addon "url tester", et si je presse "X" ca freeze aussi mais juste 3/4s.
Ceci dit pour le moment Youwatch fonctionne, j'ai testé 3 videos, toutes ont demarré en moins de 10s. Donc vais attendre que ca redeconne pour confirmer mes tests.

**Comment by LordVenom** [comment]
Nop tu as la main mais ça vas être chiant tu as un while not xbmc.abortRequested: dans la fonction run de la tu doit pouvoir faire des pauses mais je sais pas trop comment vas reagir kodi.

**Comment by TmpName** [comment]
Je viens de tester, en fait j'ai retrouvé de vieux lien youwatch qui mettent plus de 2 mn a s'ouvrir, alors : 
1 - Non plus, ce n'est pas la ou ca bloque, j'ai essaye de trace la fonction run() et je passe juste une fois dessus, pas de boucle
 >>17:37:38 T:1760  NOTICE: DVDPlayer: Opening: h ttp://fs51.you watch.org:8777/xxxxxxxxxxxxxx/video.mp4
17:37:38 T:1564  NOTICE: Thread DVDPlayer start, auto delete: false
17:37:38 T:1564  NOTICE: Creating InputStream

A partir de la, ca commence a mouliner, le lien est deja decodé, je presse "X"

>>17:37:49 T:1564   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://fs 51.youwa tch.org:8777/xxxxxxxxxxxxxx/video.mp4
17:37:54 T:1760  NOTICE: CDVDPlayer::CloseFile()
17:37:54 T:1760  NOTICE: DVDPlayer: waiting for threads to exit

Et c'est la ou ca freeze, puis au bout de quelques secondes

>>17:38:10 T:1564   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
17:38:10 T:1564   ERROR: CCurlFile::Open failed with code 0 for ht p://fs51.youw atch.org:8777/xxxxxxxx.mp4

Mais ce n'est pas Vstream, j'ai testé l'url dans url tester tool, pareil ca freeze.

Et quand je dis freeze, c'est gros freeze, j'ai meme droit a "kodi (ne repond plus)"

**Comment by LordVenom** [comment]
J'ai plus d'idée la, sur internet il parle de problème de décodage dans la lib  libmicrohttpd-0.9.35 a remplacer par libmicrohttpd-0.9.34-1 mais ça m'aide pas plus.

**Comment by TmpName** [comment]
Ca deconne aussi chez vous, ou c'est juste moi ?

J'ai regardé vite fait  libmicrohttpd mais ca ne gere pas uniquement la partie WebServeur ce "truc" ?

**Comment by LordVenom** [comment]
Non c'est pas toi, c'est pour ça que j'ai creer la popup cancel pour les chargement pour éviter les plantage de timeout.

**Comment by LordVenom** [comment]
A tu vue ça jamais modifier mais bon

http://kodi.wiki/view/HOW-TO:Modify_the_video_cache

**Comment by TmpName** [comment]
Bon quelques tests qui ont marché, mais la je dois laisser tomber, tout les hosts marchent a fond ..
>># SET DEFAULT TIMEOUT FOR SLOW SERVERS:
socket.setdefaulttimeout(240)

Ca je sais pas comment ca marche, mais par contre
>>return True, r[0] + '|connection-timeout=240'

Ca marche pas mal, oui j'ai du mettre le timeout a 4 mn pour avoir quelque chose, bon me faut encore tester, mais si ca marche suffirait en cas de timeout (sur une liste de host peu fiable comme youwatch) de proposer un autre essais mais sur 4 min en expliquant que tout va etre gelé pendant ce temps

**Comment by LordVenom** [comment]
J'ai vue y longtemps un plugin qui proposer un preload mais impossible de remettre la main sur ce code.

**Comment by TmpName** [comment]
Bon quelques news, chnager juste le timeout ne marcherait pas, il faut chnager 2 options
>>         <curlclienttimeout>240</curlclienttimeout>  
         <curllowspeedtime>240</curllowspeedtime>

**Comment by canopre** [comment]
Testé sur raspberry 2 et pas vraiment vu de différence...
