### ISSUE TITLE
Poypi

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#76]
Comme le site Poypi est out, est-il possible de le remplacer par FADOZ http://www.fadoz.com/rva/ qui est toujours en ligne?

**Comment by TmpName** [comment]
Personnellement j'attendrais quelques jours pour voir si c'est definitif, en attendant donne moi un peu de temps pour trouver la cle de fadoz, et je te remet Fadoz en place.

**Comment by TmpName** [comment]
Bon j'ai remit en place Fadoz avec sa cle decodée > https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/fadoz_com.py

Mais je le met pas dans la version officielle car poypi va bientot revenir (panner serveur) et il y a deja trop de sources.
