### ISSUE TITLE
Cinemey

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#77]
J'ai rajouté le site Cinemay dans sites mais malheureusement il ne s'affiche pas dans vStream?

**Comment by LordVenom** [comment]
Chez moi ça fonctionne enfin le debut du code car c'est en cours. cherche dans les films sources y a pas de nouveautés sur ce site.

**Comment by LordVenom** [comment]
J'ai fait une mise a jour et je voudrais ton avis @TmpName  surtout sur la fonction showSeries ça fonctionne a peux prés mais je suis sur qu'on peux mieux gérer ça.Le truc c'est de split le code source pour avoir le patern dans le bon sens.Mais peux être un regex bien fait c'est le faire ?

**Comment by TmpName** [comment]
On pourrait faire avec un seul regex, mais ca demanderait pas mal de gymnastique mentale, car
1 - il faudrait savoir quand commence les liste d'episode dans le gros regex (eg avec une simple fonction de recherche d'item)
2 - Detecter la fin d'une liste d'episode (eg si elle est suivi de "/<div>" ou pas.
3 - A chaque fin de liste d'episode incrementer un compteur pour lire le numero de saisons suivante.

Utiliser un simple compteur pour eviter de lire les saisons, je ne pense pas que ce soit une bne idée car pas dit qu'il n y ait pas des saisons qui commence a 2 ou 3 au lieu de 1.

Ta methode me semble bien, en plus vu que tu utilises un regex pour recuperer la partie de code interessante, puis un autre regex juste dessus, ca ameliore la rapidite de maniere tres visible, les regex trop complexes c'est lent.
Non franchement, elle est rapide, simple a bidouiller, pquoi faire compliqué.

Juste un bug pour eviter la premiere ligne vide
if aEntry[0]:
        oOutputParameterHandler = cOutputParameterHandler()
...
..
else:
      sTitle = sMovieTitle+' - '+aEntry[2]
...
...

**Comment by LordVenom** [comment]
ok merci
