### ISSUE TITLE
Protection Clo_ud Flar e

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#78]
Bon ca y est j'ai finallement fini le fichier, en fait je suis tombé sur un site qui etait protege 24/24 7/7 avec une remise a zero des cookies plusieurs fois par heures (je sais pas si c'est normal, ou si le webmaster est un grand parano)

Donc il y a 2 methodes pour s'en servir, detailées dans le fichier, une methode brute, qui cherche systematiquement la protection, et une methode light qui ne marche que si la methode normale ne marche pas.

Il y a egalement une fonction speciale pour les fichiers comme les images (qui sont egalement protegées du coup)

Le site pour tester https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/series_en_streaming_tv.py
Je l'ai laissé dans le repertoire trash le temps de tests.

Le code est a nettoyer (y a des bouts en anglais d'autre en francais, beacoup de debogage ...)

Un seul probleme, la 1 er fois que le cookie est crée, le chargement rate, il faut le relancer une seconde fois pour avoir le code html, normallement ca devrait passer, je sais pas encore pkoi. J'ai essayé avec une tempo > pareil.

cf https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/lib/cloudflare.py

Pour la gestion des cookies j'utilise une fonction maison car on utilise pas les cookies dans Vstream, pour le moment ca suffira.

**Comment by TmpName** [comment]
Bon j'ai trouvé mon bug mais pas la solution

>>         opener.addheaders = self.headers

            print self.headers
            opener.addheaders.append (('Cookie', cookies))
            print self.headers

En fait ca ne fait pas une copie, mais opener.addheaders se trouve lié a self.headers, tout changement a l'un change l'autre, c'est comme une copie de pointeur en c++

Et comme en python on ne peut pas modifier ou suprimer un tuple, .......

**Comment by LordVenom** [comment]
Tu as regarder la fonction inclus dans l'addon pour les cookies ?

aHeader = oRequestHandler.getResponseHeader()
sReponseCookie = aHeader.getheader("Set-Cookie")

J'ai pas trop suivis mais si ça peux t'aider.

**Comment by TmpName** [comment]
Pas de bol (decidement ....), protection retirée ce soir, plus de tests possibles ....

**Comment by TmpName** [comment]
Bon c'est bon site reprotegé ^^.

Tout est ok, le fichier site et le fichier bypass Cloudflare.
Tout se passe du premier coup, et sans ralentissement.
