### ISSUE TITLE
TODO list.

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#79]
Mettre un dialog avec progress bar, lors d'une recherche globale.

**Comment by LordVenom** [comment]
Y en a un non ? enfin plusieurs ça vas être compliquer de les imbriquer dans 1 seul.

**Comment by TmpName** [comment]
Nope, j'en ai pas vu quand je fais une recherche globale, ou la recherche visuelle, et ca peut etre long (vu le nbre de sources)
En fait j'ai meme pas regardé si c'etait possible ^^.
Je l'ai juste marque la pour ne pas oublier, j'y jete un oeuil dans la semaine, la suis encore sur ce probleme de timeout qui me pourrit la vie, hier soir j'avais 4 hosts de mort qui auraient pu marcher avec le temps.

**Comment by TmpName** [comment]
Bon j'ai testé >>http://pastebin.com/FBhXAjGV
Ca marcherait mais probleme, pas moyen d'avoir 2 progress bar, quand on créé la seconde ca met le bordel. Et pour chaque site il y a en une dans showmovies

2 possibilitées.
1 - Modifier chaque source pour ne pas afficher la progress bar en cas de recherche. (trop long)
2 - modifier le code pour ne pas afficher de progress bar, si il y en a deja une a l'ecran.

**Comment by LordVenom** [comment]
La popup de showmovie et trés utile pour les sites avec pas mal de contenue ou quand les meta sont activer.
donc oui si tu veut 1 popup dans la recherche il faudras modifier tout les sites pour virer la popup des recherche.

**Comment by TmpName** [comment]
^^, ouais mais la, ca va etre la misere pour pas grand chose. Je ne veux surtout pas supprimer la popup de showmovie.

Je vais voir si je trouve une solution plus simple

**Comment by TmpName** [comment]
Bon pas possible sans grosses modif, enfn du moins j'ai pas trouvé

Soit on crée la fonction cConfig().iscanceled(dialog, total) et on modifi tout les sites.
Soit on crée la fonction cDialog carrement dialog = cDialog().createDialog(SITE_NAME) et la encore plus de modifs.

Donc on va garder de coté pour le jours ou y aura besoin de grosses modifs.
