### ISSUE TITLE
source streamzzz.com

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons-beta#8]
Il y a juste un truc pour une longue serie faisant appel au bouton next (ex:alf) au dessus du bouton next il y a un espace peu etre arrive tu a le faire disparaitre

**Comment by TmpName** [comment]
Alors 2 choses j'ai rendu le pattern plus restrictif il ne prend que les lien comprennant "http://streamzzz.com/page"
mais ce qui fout la merde c'est l'autre partie, la premiere partie, il faut la supprimer si elle ne sert pas ou la modifier mais je n'ai pas trouvé ou tu t en sert.

Un pattern qui fonctionne, mais suis pas sur qu'il soit suffisant 
http://pastebin.com/zmMw1fmw

**Comment by FreeFighter77** [comment]
Merci a toi une fois de plus,en faite je ne savais pas restreindre a streamzzz.com donc dans ma pattern j'ai restreind comme je pouvais :p mdr
Donc grace atoi voila ce que ca donne:
http://pastebin.com/WTq1ycHy

**Comment by LordVenom** [comment]
Une recherche et possible via http://streamzzz.com/search/ma recherche

**Comment by FreeFighter77** [comment]
J'ai testé sous kodi ca ne marche pas,j'ai vu que tu avais egalement rajouté la recherche pour regarder-films,le probleme est qu'il recupere tt les episodes (je trouve que ca fais fouilli) qu'en pense tu ?

**Comment by LordVenom** [comment]
Si le site propose une recherche et qu'elle est simple a faire, je la fait, l'utilisateur peux toujours désactiver la recherche de ce site dans les paramètres.
