### ISSUE TITLE
Telechargement fichier

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#81]
Ouais je sais, je commence plein de truc sans les finir mais pour info je suis en train de rajouter une file d'attente pour les telechargements.

J'attend la prochaine mise a jour, pour partir sur des bases propres, mais ca va rajouter sur le "home" un partie telechargement.
Aucun demarrage auto, c'est a l'user de demander le depart des telechargements,

Pas de reprise, ni de pause pour le moment.

**Comment by LordVenom** [comment]
Tu as choisis quel system une entrer dans la BDD ou un listing d'un repertoire la Bdd et une bonne idée je pense qu'on pourais faire des entrers pour le size.

**Comment by TmpName** [comment]
Alors la, trop technique pour moi, j'ai pas compris, en fait j'utilise la meme methode que pour les favoris, je sais pas c'est bien ou pas mais memoriser 10 marque page ou mettre 10 fichier en attente, je pense que l'utilisation sera la meme.

Pour le moment c'est vraiment basique, c'est quoi les entrees pour le size? tu veux afficher les tailles de fichiers ? Pour ca c'est mal parti, a cause des liens generés a la demande, je ne memorise pas le lien resolu mais la page html de l hebergeur pour pouvoir regenerer le lien lors du DL.

**Comment by LordVenom** [comment]
Oui les marque page utilise la BDD (base de donnée) cDb().insert_history de la tu peux mémoriser le lien résolut et pourquoi pas un size c'est un idée comme ça mais dans le téléchargement de fichier tout le X data on doit pouvoir faire un update de la base.

Les lien sont générer dans download.py (il me semble) il suffis de modifier pour envoyer a la base de donner les info puis les recuperer comme le fait favorite.py.

**Comment by TmpName** [comment]
Bon je galere un pwal, je hais vraiment le python, pas moyen d'utiliser des variables relleement globale
Si tu peux jeter un oeuil >> http://www.cjoint.com/c/EJEqW3WJpox
Je n'ai pas touché aux fichier de la beta encore.

Alors j'en suis ou ?
On peut rajouter un lien en list en menu contextuel.
Il ya une liste de fichier dans le home
Leur menu contextuel possede le "demarrer download" qui fonctionne

Impossible d'arreter le telechargement car ne je peux pas memoriser la premier fois que je crée la classe.

Sur genesis ca fonctionne et pas chez moi, je comprend pas comment ca marche chez eux

J'ai commencé a mettre en place un multithreading.

**Comment by LordVenom** [comment]
Si tu veut déclarer une variable global a tous je pense qu'il faut la mettre dans default.py, mais je comprend pas l'utiliter.

Envoie sur bêta c'est fait pour et ça permettra de bosser ensemble.

**Comment by TmpName** [comment]
Ben je sais pas comment faire une mise a jour de plusieurs fichiers (et y en a beacoup de modifiés), c'est pour ca je t'ai passé un lien vers le repertoire complet sans les images.

Tu iras plus vite que moi pour faire les mises a jours, ( ou alors tu fais tout les fichier un a un aussi ?)

**Comment by LordVenom** [comment]
Perso j'utilise https://desktop.github.com/

j'ai dossier syncro avec github et un dossier travail.
je copie les fichier modifier dans le dossier syncro et github me dit ceux qui modifier puis je sync.

**Comment by TmpName** [comment]
Indispensable pour celui qui utilises souvent github.

Sinon j'ai jete un oeuil sur le code du simpledownloader, ils utilise un autre addon pour memoriser (au lieu d'une variable) http://forum.kodi.tv/showthread.php?tid=116496

Mais du coup, quite a rajouter une dependance sur un addon, autant rajouter celle de simpledownloader non ?

Je ne crois pas qu'il permette de stopper les downloads par contre, y en a qui on posé la question sur le forum (sans reponses comme d'hab).

**Comment by LordVenom** [comment]
Je pense pas que la pause et la reprise fonctionne même avec le lien decoder puisque certain lien ont besoin d'entête pour fonctionner.

Oui plugin.cache et déja dans les dépendance mais je sais plus pourquoi lol

Pour faire une liste des fichiers en cours pas besoin d'un addon en dépendance.

**Comment by TmpName** [comment]
Non je pense comme toi, reprise pas possible, je peux refournir les entetes mais vu que les lien sont generés a la volée, ca risque de ne pas correspondre, et je ne pense pas que du coup ils aient prevu cette option sur ce type de serveur.

Ben en fait je vais me servir du commoncache, pour memoriser si il y a un download en cours (si on est plus sous Vstream par exmple) et surtout l'instance de la classe.

Si tu touches pas aux fichier je pars de ma base, devrais m y mettre demaon apres midi, si tu touches aux fichiers previens moi.

**Comment by LordVenom** [comment]
Ok hâte de voir ça,

**Comment by TmpName** [comment]
Bon je laisse de cote pour le moment.
J'ai finallement mis les fichier a jour a la main (plus de 100M pour ton appli juste pour synchroniser des fichiers ?????)

Alors dans la liste de fichier seul le menu contextuel marche.

Ca marche mais c'est assez lourd, a chaque cycle je fais un appel au commoncache pour savoir si je dois continuer
J'ai essayé de memoriser l'instance avec
self.Memorise.set("VstreamDownloaderClass", repr(self))
Ca marche, mais impossible de m'en resservir dans la fonction StopAll, vu que c'est un str now, et pas moyen de reconvertir.

Manque plein de dialog partout, eg si la personne veut arreter, demander si elle veut le faire now ou apres le dl en cours.

La file d'attente ne marche pas encore, quand un fichier se fini, c'est fini.

J'espere avoir mis tout les fichier, sinon, tu auras forcement le manquand dans le zip quelsques post plus haut.

**Comment by LordVenom** [comment]
Chez moi ça ne tourne pas, j'ai fait des modif pour afficher la popup de renamme mais téléchargement impossible.

17:57:26 T:6384  NOTICE: 	[PLUGIN] Vstream: Telechargement http://videomega.tv/iframe.php?ref=fGJbbJZNQHHQNZJbbJGf&width=640&height=480
17:57:26 T:6384  NOTICE: http://videomega.tv/iframe.php?ref=fGJbbJZNQHHQNZJbbJGf&width=640&height=480
17:57:30 T:6384  NOTICE: 	[PLUGIN] Vstream: Rajout en liste de telechargement http://videomega.tv/iframe.php?ref=fGJbbJZNQHHQNZJbbJGf&width=640&height=480
17:57:30 T:6384  NOTICE: 	[PLUGIN] Vstream: Telechargement impossible

**Comment by LordVenom** [comment]
C'est quoi ce menu demarrer / aretter je pensé que c'etait pas possible la reprise d'un téléchargement.

Donc context menu télécharger logiquement le téléchargement demarer et ce met en liste en cours.
et la a pars voir l'etat du Téléchargement je voie pas quesqu'on peux faire.

**Comment by TmpName** [comment]
Essayes avec un lien exashare, ils telechargent pas mal.

Sinon j'ai mis a jour le fichier download, regarde l historique, tu vas comprendre mon oubli.

**Comment by TmpName** [comment]
Bon petite modif, now il gere les fin de download.
Mais probleme pour lancer le thread, en mode normal il freeze tout, je pense qu'il faut utiliser le deaomon mode
> https://code.google.com/p/navi-x/source/browse/trunk/Navi-X/src/CDownLoader.py?r=155

**Comment by LordVenom** [comment]
Dsl je comprend pas ceux que tu tente de faire.

**Comment by LordVenom** [comment]
ATTENTION mise a jour de la base de donner il faut supprimer l'ancienne pour voir les modif.C'est encore un peux brouillon mais ça mais dans la BD l'evolution du téléchargement.

**Comment by TmpName** [comment]
Moi non plus ^^.
En fait j'avance petit a petit, ma derniere modif etait pour effacer un fichier de la liste quand le dl est fini (mais je crois que ca ne marche pas)

Pour le coup du thread c'est simple, quand tu lance le dl en menu contextuel ca marche, mais si tu essaye en passant par le "download" qui est sur la premiere page (remplace "dummy" par "StartDownloadList" ligne 258), ca bloque durant le dl, en fait je cherche a la faire passer en arriere tache, pour ne pas bloquer Kodi.

La deuxieme chose que j'essaye de faire, c'est d'acceder a communcache et la base de donnée le moins possible, car je crois que kodi ecrit et lit sur le disque dur a chaque fois (mauvais pour performance), donc je cherche a tout virer de la fonction "_StartDownload"

Mais si kodi utilise ses bases en memoire vive, et les met a jour a la fermeture (ce qui m'etonnerait) je me fais chier pour rien.

**Comment by TmpName** [comment]
Bon quelques correction mais ca commence a me courir sur le haricot ce language de merde.
Pour me passer du commoncache me suis dit que je vais donner un nom a mon thread. Ca marche visible en debug log.
Mais quand j'essaye de lister les thread, ben il apparait pas dans la liste, pourtant je le vois tourner de mes yeux, la progress bar bouge........

**Comment by LordVenom** [comment]
Ouf dur dur Bon chez moi ça afficher une popup de load infinie aprés x recherche ça vient de addDir qui et coder pour attendre une réponse, comme je peux pas modifier addDir, donc j'ai utiliser la méthode de base pour creer un lien et ça tourne.

**Comment by TmpName** [comment]
Nooon, me dis pas que c'etait ca le probleme ????
J'y ai passé plusieurs heures a essayer plusieurs methode pour le threading en pensant que l'erreur venait de ca !!!

**Comment by LordVenom** [comment]
tout marche comme tous le voulais maintenant ?

**Comment by TmpName** [comment]
Oui oui, suis degouté, now je me penche sur le moyen de recuperer le nom du thread.

**Comment by TmpName** [comment]
Bon rien de nouveau mais j'ai une question.
>>Class Class1():
    def getval(self,a):
           print self.val
    def setval(self,a)
           self.val = a

Si je fais
>>Class1 Classe1()
classe1.setval(10)
Class1 Classe1()
classe1.getval()

Je n'aurais pas la valeur 10, c'est normal, vu que je cré une nouvelle classe, mais comment faire pour acceder a la premiere, c'est bien possible, j'ai vu des addon le faire, mais comment ?
Sachant que la premiere partie peut etre appelle par le premier menu et la seconde par un autre menu donc pas possible de memoriser Class1.

**Comment by LordVenom** [comment]
SI tu fait a = cdownload() puis a.kill tu apelle la fonction kill de cdownload

 def kill(self):
        self.killed = True

**Comment by TmpName** [comment]
Yep, la j'ai posé une question sur un forum, demain je nettoie un peu le code pour t expliquer mon probleme, la il y a plein de code perso pour deboguer et ca rend le code incomprehensible.

**Comment by TmpName** [comment]
Vla, j'ai mis en ligne une version plus propre.
Le menu "arreter" fonctionne encore, ca evite d'avoir a redemarrer kodi pour arretter le DL.
En fait j'essaye de faire fonctionne le menu "Arreter Beta", tu vas vite voir mon probleme.

J'essaye de ne pas utiliser le commoncache car lourd en accee disque.
Il y aurait plusieurs moyen :
1 - Passer self.processIsCanceled a True mais celui de la bonne instance
2 - Fermer le dialog de la progressbar
3 - Arriver a fermer le thread, il y a moyen de chnager le nom pour qu'il soit plus facile a trouver mais ca ne m'a pas aidé.

**Comment by LordVenom** [comment]
Je suis passer par un setting de l'addon je sais pas pourquoi mais toute mes tentatives avec les class n'ont pas fonctionner.
Perso je penser virer la barre de progression puisque ça ce met a jour sur la page des téléchargement , je suis pas fan de la barre que tu peux pas masquer.

**Comment by TmpName** [comment]
En fait en passant par les classes, ce ne marche pas car tu a chaque appel tu crée une nouvelle classe alors qu'il faudrait recuperer l'ancienne. Je n'arrive pas a comprendre comment ils font sur les autres addons.
Dans le debug tu as la ligne "Thread actuel" qui devrait toujours avoir la meme valeur.

En fait la barre de progression est utile car elle permet de savoir qu'il y a un DL en cours, meme si on est ailleurs que sur Vstream. Et pareil si on arrive a recuperer la classe de la progressbar, il suffirait de la fermer pour que ca marche, mais pareil meme en recuperant sonID je ne peut recuperer les "adresses" des classe au format STR non reconversible en "adresses".

Et la commande cConfig().setSetting utilise aussi des accee disque, donc meme probleme que moi avec le commoncache.

**Comment by TmpName** [comment]
J'ai trouvé un nouveau code >> http://kodi.wiki/view/HOW-TO:Write_Python_Scripts#Download_Files_with_Progressbar

Une version plus avancé utilisé dans Icefilm >> https://github.com/Eldorados/icefilms-addon/blob/master/plugin.video.icefilms/resources/lib/DownloadInBackground.py

Qui gererait l'interruption.

**Comment by LordVenom** [comment]
Oui peux créer c'est propre dialog mais ça

**Comment by TmpName** [comment]
Oui c'est la BDD, mais dans la mesure ou en cas de plantage, les donn"es sont memorisées, cela veut dire que kodi les inscrit sur le disque a chaque fois et non pas lors de la fermeture.

Bon sinon j'ai trouvé une methode qui marche, cf fichier.

Par contre une methode qui ne marche pas et je ne sais pas pourquoi (dans StopDownloadListBeta)
>>    WINDOW_PROGRESS = xbmcgui.Dialog( 10101 )
        WINDOW_PROGRESS.close()

Et une autre methode que je n'ai pas le temps de tester avec les "builtin" fonction RunScript(script[,args]*)
et StopScript(id)

Il suffirait de faire un script juste pour le DL et de le gerer avec ces 2 fonctions.

**Comment by TmpName** [comment]
Alors ? Verdict ? on continu sur ca ? ou on teste encore d'autres solutions ?
Je viens de voir un addon qui utilise la meme technique http://kodi-passion.fr/addons/?Page=View&ID=script.module.dialogaddonscan

**Comment by LordVenom** [comment]
Je te fait confiance pour prendre la dernière décision par contre moi ceux que j'aurais aimer c'est que dans la liste des dl ont puisse les lires, les supprimer définitivement (dur disque).

**Comment by TmpName** [comment]
Ha yep.
Moi perso je les telecharge direct dans le bon repertoire, donc c'est géré directement par kodi.
Mais je vois ou tu veux en venir, surtout pour ceux qui vont passer par ca pour avoir des stream d'avance quand les serveurs sont out ou qui se foutent de les conserver par exemple.

Demain vais mettre ca en place avec un systeme de couleurs, mais je sais meme pas comment presenter le smilblik.

1 couleur DL en cours
1 couleur DL fini
1 couleur pas DL

ou carrement 2 folders different pour DL en cours et DL finis ? Plus simple a gerer avec un menu contextuel.

**Comment by LordVenom** [comment]
Le système de couleur me semble bien en plus y a une table status dans la bd download qui pouras faire le distinguo

**Comment by TmpName** [comment]
Bon grosse mise a jour.
Pas mal de truc en plus fonctionnent, d'autres pas encore, pour le detail, je te laisse tester.

Edit:
A finir:
"Supprimer fichier" du disque dur
Mettre les textes dans le fichier langue
Esthetique.
(A suivre)

**Comment by LordVenom** [comment]
J"ai modifier la fonction play chez moi ça charger dans le vide.

**Comment by TmpName** [comment]
Bon ben encore une petite mise a jour, je vois plus trop quoi d'indispensable a faire, a part tester tout les host pour savoir lesquels ne permettent pas le DL.

Si tu n'as pas d'idée non plus, on peut demander des testeurs sur la VO, y avait quelqu'un avec des prb de dl justement.

**Comment by LordVenom** [comment]
J'ai modifier la suppression qui etait bizard pour moi, j'ai ajouter une function pour eviter les doublons. surtout sur les series qui prenne pas en compte l'episode a voir si ont peux améliorer le choix du titre.

**Comment by TmpName** [comment]
Pour le choix du titre on peut utiliser une variante de la fonction qui colore les titres, elle converti en SXXEXX.

**Comment by arzaz** [comment]
Bonjour,

Je viens d'installer la version download beta, mais je ne sais pas si elle est fonctionnelle? car chez moi quand je lance un téléchargement j'ai toujours l'erreur "Erreur Script! vStream"

**Comment by LordVenom** [comment]
J'ai fait quel modif graphique, pk avoir re-toucher la suppression ? elle ne supprimer plus du disque.

@arzaz : Merci de faire le bêta testeur si tu pouvais être beaucoup plus précis (ou? quand? comment?) et retourner l'erreur ecrite dans le log merci.

**Comment by TmpName** [comment]
Il y a 2 suppression dans le menu contextuel "Effacer de la liste" et "Effacer fichier", seule la seconde supprime les fichiers.
Moi quand je dl les fichiers ils vont dans un repertoire special, et je les regarde parfois 15j apres, c'est pour ca que j'utilise la fonction pour les virer de la database sans les effacer.

**Comment by LordVenom** [comment]
Ha ok moi j'ai que "effacer de la liste" dans le context d'ou le problème.

Ok si ont stop un fichier en cours ont doit pouvoir le supprimer du disque si ont a changer d'avis par exemple.

Je comprend pas si j'effacer un fichier il doit etre supprimer de la base et du DD
Il faut résonner comme si l'utilisateur n'avais que vStream pour gerer c'est fichier.Il doit pas repasser par xbmc puisque l'addon le fait.

**Comment by TmpName** [comment]
Ha wi mince, j'ai pas pensé au telechargement interrompu, corrigé normallement ATM.

Mais par contre, les deux actions doivent rester possible pour moi, si je veux garder mes fichiers sans vouloir une liste de 30 fichiers dans Vstream.

**Comment by arzaz** [comment]
Bonjour,

Test effectué sur la boxe Prismcube ruby sous Gotham 13.2
Site: Frenchstream
Film: Transporteur heritage
Host: Videomega
Erreur: echec script! Vstream
Ci-dessous le debug Log.
http://xbmclogs.com/p9ogcyxeq

**Comment by TmpName** [comment]
Ha oui "ImportError: cannot import name cDownload"
Normallement ca n'aurait pas du passer par la, tu es sur d'avoir copier l'integralité des fichiers ?

>>
File "/home/root/.xbmc/addons/plugin.video.vstream/default.py", line 67, in parseUrl
                                                exec "from resources.sites import " + sSiteName + " as plugin"

normallement ce n'est pas ca la ligne 67

cf https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/default.py

**Comment by LordVenom** [comment]
J'ai fait encore quel modif, par contre j'ai trouver un bug, lance un téléchargement et coupe xbmc. quand tu revient tu peux plus lancer de DL il considère qu'il y en a 1 encore en cours.

**Comment by TmpName** [comment]
Oui, mais j'y ai pensé normallement y a une fonction en cas de bug, qui doit pas marcher, mais qui est presente, vais voir ca ce soir.

**Comment by TmpName** [comment]
Bon c'est bon ca marche mieux en cas de blocage, deux possibilitées.
1 - selectionner "arreter la liste" dans le menu
2 - click droit sur le fichier bloqué, "arretter"

D'ailleurs le menu "arreter la liste" arreter les download en general, meme si l'user en a demarré un seul sans demander la liste complete, c'est pour ce que je l'avais appelle juste "arreter"

@arzaz ca ne marche tjours pas chez toi ?

**Comment by LordVenom** [comment]
Nickel pour le moment je touche plus.
