### ISSUE TITLE
ameliorer les informations du film/serie

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#82]
En menu contextuel, "information" pourrait donner plus d'infos, scrapées sur un autre site, eg trouver un resumé quand pas dispo.

Ps : je me renseigne pour le moment, mais pourrait m'y mettre dans la semaine, si la partie DL n'a pas besoin de grosse modif, je pense qu'on peut demander a quelques users de donner leurs avis/bugs.

Edit: Heu si tu passes par la, tu as l'air de mieux gerer l'api de themoviedb que moi ^^, tu aurais la commande pour avoir l' "id" d'un film/serie pour pouvoir le lui renvoyer pour avoir les infos, ou mieux si tu vois ce que je cherche ....

Edit: C'est bon j'ai trouvé mais le resultat pique
h ttp://a pi.themoviedb.org/3/search/movie?api_key=###&query=spiderman

**Comment by LordVenom** [comment]
Oui il faut utiliser la base de https://api.themoviedb.org/ je l'utilise pour la recherche visuelle dans the_moviedb.org.py avec l'api et le retour en json

**Comment by LordVenom** [comment]
Si un personne active les meta l'id et dedans et donc les info sont entiere. 
Maintenant si au click tu veut les info d'un seul c'est plus compliquer j'avais dejas tester mais sans succes.Car il faut faire la recherche par nom et recharger la page info c'est la que j'ai bloquer.

**Comment by TmpName** [comment]
Ha ok, en fait moi j'ai les meta desactivee c'est pour ca que c'est vide pour certain cas.
Du coup je sais pas si c'est trop utile. En fait j'ai commencé mais si tu fais une recherche pour spiderman comme l'exemple ci dessus, tu as 10 resultats au moins, et il te faut trier, et tu prend le risque d'avoir 3 fois sur 4 les infos d'un autre film.
En fait je cherche a rajouter des options deja presente dans ton code mais desactivées car bugguées/incompletes.
Par exemple la fonction "bande annonce" pourrait marcher avec juste une recherche sur youtube avec le nom du film, sans passer par les metas.

**Comment by LordVenom** [comment]
Le vrais plus serais de pouvoir charger les info d'un seul film avec le menu context information.Une popup qui afficherais le choix des films trouver et on aurais les info du films séléctionnner.

**Comment by TmpName** [comment]
Ca c'est faisable, je peux m'en occuper mais je sais pas si c'est utile, si l'user veut des infos d'activer les metas ca ne suffit pas ? (je sais pas, pas encore testé les metas, ouais je sais y a juste un click mais vais pas me faire un avis en 1 heure)

**Comment by LordVenom** [comment]
Je suis comme toi les meta ne sont pas activer et pour quel raison, le chargement j'aime pas ça lol mais je serais pas contre avoir les infos d'une serie ou d'un film qui pourais m'interesser.Donc l'idée et bien.

**Comment by TmpName** [comment]
Heu, je bloque deja ^^.
Comment rajouter des infos "a la volé", j'essaye ca mais sans succés

>>    def viewinfo(self):
        oGuiElement = cGuiElement()
        oInputParameterHandler = cInputParameterHandler()

        sTitle = oInputParameterHandler.getValue('sTitle')
        sId = oInputParameterHandler.getValue('sId')
        
        oListItem = xbmcgui.ListItem(oGuiElement.getTitle(), oGuiElement.getTitleSecond(), oGuiElement.getIcon())
        oListItem.setInfo( type="Video", infoLabels={ "Title": 'titre',"Plot":'description',"rating":'rating'  } )

        xbmc.executebuiltin( "Action(Info)")

**Comment by LordVenom** [comment]
oGuiElement.addItemValues(sItemKey, mItemValue)

**Comment by TmpName** [comment]
Bon apres quelques recherches, ce ne serait pas possible, tu peut lire les infolable, mais pas les editer une fois le directory cree.

Donc faudrait refaire une fenetre pour afficher les infos.

Je vient de voir dans mes addon Extendedinfo, le resultat dechire mais vraiment tres lourd.

**Comment by LordVenom** [comment]
Moi j'ai trouver un debut de piste aussi 

        xbmc.executebuiltin("Action(Info)")
        WND = xbmcgui.Window(12003)  # Video info dialog
        WND.getControl(400).setText('testtt')
        WND.show() 

le premier coup ça marche pas le 2eme oui manque un reload ou un time peux être
Par contre il faut qu'il y est un id dans le xml et malheuresement c'est pas le cas tout le temp, peux etre copier le xml et le modifier pour creer notre propre fenettre.

**Comment by TmpName** [comment]
Pour ce qui est de faire notre propre xml/window, j'ai trouvé un tuto pas mal > https://github.com/dersphere/script.demo

**Comment by LordVenom** [comment]
TU te lance ou je le fait, il reste ça et libre tv a recoder j'ai les info de grab si tu prefere ça.

**Comment by TmpName** [comment]
La, je corrige Youwatch, et suis sur alluc, d'ailleurs faudra que je t en parles plus tard car il est assez dur a gerer sans interface pour les series, mais j expliquerais ca sur le post en question.

LibreTv je suis au courant de rien par contre, donc ca tu es plus avancé que moi.

**Comment by LordVenom** [comment]
Ok je regarde ça, libretv peux attendre, il faudra tous refaire, la source a changer mais le createur du projet ma fournir les nouvelles sources.

**Comment by TmpName** [comment]
Attend tu me fait peur, c'est pas juste le lien du fichier m3u qui a changé ?

**Comment by LordVenom** [comment]
lolll Nop c'est du dat maintenant j'ai pas regarder si il suffis de modifier l'url mais j'ai un doute.

Bon j'ai avancer ça commence a afficher quelque chose cette popup, j'avance encore un peux avant d'envoyer sur le bêta.

**Comment by TmpName** [comment]
Je viens juste de voir ta mise a jour. Ca marche nickel.
Par contre j'ai pas compris pkoi il y a 2 fichier xml pour les dialogs ? Il y en a un que j'ai pas vu ?

**Comment by TmpName** [comment]
C'est bon j'ai trouve pour la langue.

**Comment by TmpName** [comment]
Bon j'ai commencé un truc http://pastebin.com/eXFnCaL2

Et je propose de virer les fonctions themoviedb du fichier du meme nom se trouvant dans le dossier "site", en utilisant la fonction SearchDB() du pastebin, le fichier pastebin se trouvera dans le repertoire lib

**Comment by LordVenom** [comment]
1: Erreur d'upload j'ai virer le xml en trop

2: Quand les meta sont activer les infos reste puisque c'est xbmc qui gere, avec notre system d'info c'est pas possible, j'ai pas trouver comment et refaire un menu info c'est pas supers utile.
Tu cherche le film que tu veut voir ok quelque info en plus c'est cool, une foix que tu as decider fini tu vas plus voir peux importe les host c'est le même film.

3: Dans les préférence de l'addon "paramettre des meta"

4: sFilename et une version clean du titre pas de couleur ou d'accent normalement.

Sinon pour les multiples titre je voie pas en travail ceux que ça vas donner.Les fans de meta donner et fanart peuvent activer les meta de base si c'est pas le bon titre il faut voir si ont peux ameliorer avec un filtre de titre par exemple une recherche de Hant man ne trouve rien mais Hant_man trouve.C'est dans les sites qu'il faut gerer ça pour moi l'important c'est que la même réponse soit donner mêta activer ou pas.

**Comment by TmpName** [comment]
2 - ok, je laisse tomber du coup
4 - La c'est la jungle, il y a plusieurs generations de fichiers sites et y a de tout dedans.

En fait fait "information" sur le film taken 1 puis taken 2 puis taken 3, tu vas avoir 3 fois les memes infos celle de taken 1.

La j'ai bien avancé de ce cote http://pastebin.com/mDDmrNxC

Tu as 2 fonctions
def SearchMovie(sSearchText,year=''):
def SearchSerie(sSearchText,year=''):

Qui te retourne le bon ID, c'est plus efficace, et propose un choix en cas de probleme.

def GetSerieSXXEXX(sid,title):
Lui peut carrement retourner les infos d'une serie par episode.

**Comment by LordVenom** [comment]
Si tu fait un print dans config de sFileName tu verras que c'est l'addon qui lui envoie Taken a chaque foix mauvaise gestion des titres quelpart qui vire les numeros.

**Comment by TmpName** [comment]
Yep, je viens de voir ca.
Ca marche mieux si tu tu utilise sTitle au lieu de sFileName
>>        #1 film #2serie
        ui = cConfig().WindowsBoxes(sTitle, sMeta) 

Du coup pour le moment, je laisse tomber ^^, vu que ca marche mieux now.

**Comment by LordVenom** [comment]
j'ai peur pour sTitre et les accents.Faut vraiment regarder le traitement du texte avant de modifier.

**Comment by TmpName** [comment]
Mon code les nettoye aussi, je vais voir a l'adapter pour ton code.

**Comment by TmpName** [comment]
Ok fonctionne pour film et serie, 
Mais du coup on utilise l'addon de meta qui sauve en base sql, pour les trailers il est pas au point non plus, ou le code le gere pas encore.

On rajoute une partie qui cherche des trailers sur youtube ?

**Comment by LordVenom** [comment]
Si le meta retourne une url pour le trailer un bouton bande annonce apparais dans la popup.

**Comment by TmpName** [comment]
Mais si il  ne le trouve pas, (et c'est frequent) doit y avoir moyen de chercher nous meme sur Youtube nope ?

**Comment by LordVenom** [comment]
Je pense que l'addon youtube doit avoir une fonction de recherche par nom, mais est ce que ça donneras le bon resultat a coup sur j'ai un doute et il faudrais chercher a la demande et nom en avance afin de limiter les requêtes.

**Comment by TmpName** [comment]
Yep, si j'ai le temps je regarderais ca ce WE, car sur youtube "BA nom_d_un_film' marche asssez bien.

**Comment by TmpName** [comment]
Mise en place d'une version beta pour les bande annonce.
