### ISSUE TITLE
Nouvelle source

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#83]
Je viens de tomber sur ca
ht tp://w ww.alluc.ee/

C'est assez puissant, ca fait une recherche globale sur les sites que possede deja Vstream et encore d'autre, et le mieux c'est que j'ai fait plusieurs test, et je tombe jamais sur youwatch ou exashare ni sur des liens mort.

Vos avis ?

Ca marche pour film et serie

A coupler avec la recherche visuelle ?

**Comment by LordVenom** [comment]
Rien de trés visuelle la dedans pas d'information, mais il faut que la recherche visuelle sans servent donc il faut creer un site avec juste une recherche le reste seras automatique.Puis ont peux creer dans la recherche de base une section special pour ce site qui devrais etre plus rapide que notre recherche global.

**Comment by TmpName** [comment]
Ben en fait le gros avantage de Vstream sur Genesis c'est justement que la recherche et puissante, est comme c'est l'user qui choisit le resultat, ils sont garantis a 100/100.Donc pour cette raison je prefere ne pas toucher a la recherche de Vstream.
Par contre la recherche visuelle est plus pour les neophytes et apres quelques tests je peux meme dire que Vstream est moins performant si tu recherches un film en passant par elle (a cause du filtrage des mots cle)
Moi je pensais faire une version light justement pour neophyte, l'user passe par la recherche visuelle et quand il choisit ca y propose soit la recherche par le moteur de Vstream soit par alluc.
Et si il passe par alluc juste afficher une liste de resultat
Site / host / VF[VOSTFR

teste par exmple h ttp://w ww.alluc.ee/stream/arrow+S02E04+lang%3Afr pour les series

Il faudra filtrer les fichier FR (meme en demandant les resultats francais tu as de tout, par rapport au drapeau, c'est fiable), mais ca donne une liste de hoster de qualité (pas de youwatch et tu peux selectioner un ordre de priorité des hosts) et certains sur des petits sites non géré par Vstream.

Par contre c'est plus simple mais pas de garantis sur les resultats.

**Comment by LordVenom** [comment]
ok donc tu veut proposer 2 recherche a la recherche visuelle, jusque la ok 

Je click sur mon film il me dit vStream ou alluc 
dans ce cas dans recherche je peux aussi mettre vstream ou alluc.

**Comment by TmpName** [comment]
Heu, en fait j'avais pas pensé a ca.

Oui, c'est possible avec un petit commentaire expliquant les plus et moins de chaque moteur, mais faudrait trouver un moyen de mettre celui de Vtream en valeur par rapport a alluc, car au bout de 3 / 4 recherches sur alluc ca peut donner un sale avis sur Vstream.

C'est comme si tu te faisait un avis sur google en utilisant que ca fonction "j'ai de la chance"

**Comment by LordVenom** [comment]
Je m'inquietes pas de ça temps que les utilisateurs trouve leur film et le lise depuis vStream :)

**Comment by TmpName** [comment]
Bon alors, recherche finie, reste les prbs d’esthétiquement.
Mais j'ai quelques questions pour l'implentation.
Tu as prevu de faire une second menu quand on clique sur rechercher avec "recherche Vstream" / "recherche alluc" / " Recherce visuelle" ?
Ou juste avec les 2 premiers ?

Le fichier marche en passant par "afficher toute les sources"

Par contre elle a un gros probleme, l'interface. Contrairement aux autres sites elle n'affiche pas de liste, pas trop chiant pour les films, mais pour les series ....
L'user est obligé de taper Serie SXXEXX pour avoir un resultat correct. Et ca devient vite la galere pour avoir une saison complete, alors que dans Vstream, un "back" puis suffit de selectionner l'episode suivant.

Honnettement sans le greffer sur la recherche visuelle, il est tres complexe a gerer, et sans utiliser le clavier simplement impossible.

**Comment by LordVenom** [comment]
vStream fiable mais plus complexe
alluc simple mais resultats non garantis

Lolllll énorme taff bravo.

**Comment by TmpName** [comment]
Par contre, on vient de m'envoyer en deplacement pour le taff de facon soudaine, donc va pas pouvoir tout finir d'un coup, mais y a moyen de croiser cette partie avec ton futur code pour afficher des infos, histoire de faire des fonctions qui font servir pour plusieurs partie de Vstream.

Eg Searchmeta(nom_d_un_film)

**Comment by LordVenom** [comment]
Ok je vais regarder ça, j'ai pas trop compris les nouvelles section dans themoviedb (recherche film , serie) 
- tu  cherche sur tvDb puis au click ça demande sur vstream ou alluc ça fait beaucoup de recherche lol.
Alors je comprend que si tu fait une recherche par ce system tu as l'id tmdb.Mais je voie pas la finaliter du truc.donc je touche pas.

**Comment by LordVenom** [comment]
Je me rend compte qu'il faut uniformiser la recherche par exemple il importe la recherche pour voir si il trouve puis import encore pour la recherche je pense qu'il faut integrer la recherche a recherchehandle.py,

**Comment by TmpName** [comment]
En fait le fichier alluc_ee est sur la beta dans le repertoire "trash" (a mettre adans le repertoire site)
Et oui, je trouve aussi qu'il aurait besoin d'optimiser du code, et pas seulement ici.

**Comment by LordVenom** [comment]
J ai modifier la recherche j upload demain

**Comment by arzaz** [comment]
Bonjour,
Je viens de faire le test avec la beta, en lançant la recherche avec le site "alluc.ee" j'ai echec vstream!
NB: A quoi sert le nouveau dossier "skins/default/720p"

Merci

**Comment by LordVenom** [comment]
Verifier ton log chez moi pas de soucis.Le skin nous sert a afficher notre propre popup d'information.

**Comment by LordVenom** [comment]
J'ai ajouter la recherche texte simple avec l'entrer pour l'historique.

**Comment by TmpName** [comment]
Nicel, en tout cas ca va faire une grosse mise a jour ^^.
Me sauve pour quelques jours, je croise les doigts pour qu'on ait pas oublier un pave de bug :).
Bonne semaine.

**Comment by TmpName** [comment]
Ha oui, dsl j'ai oublié un truc. J'ai supprime une source et renomme une autre sans avoir modifier le fichier de configuration setting.xml.
