### ISSUE TITLE
vroliz

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons-beta#85]
bonjour et bravo pour votre boulot !!!

serait il possible d'ajouter vroliz comme source ?
depuis peu on y trouve vraiment pas mal de sources HD, et ça fonctionne vraiment bien !
merci

**Comment by LordVenom** [comment]
Merci pour l'info ont vas regarder ça mais pas tout de suite.

**Comment by TmpName** [comment]
Non, il n'y aura pas vroliz, je viens de reverifier c'est la meme source que poypi.
poypi = vroliz= fadoz = XXXXX (mettez ce que vous voulez comme lettre a la place des X).

Il y a un addon qui propose les 2 sources mais c'est les memes liens que tu auras.

**Comment by TmpName** [comment]
Non, je viens de reverifier, il n'y aura pas Vroliz car c'est la meme source que poypi.
Vroliz = poypi = fadoz = XXXXX (mettez ce que vous voulez a la place des X.
Il y a un addon qui propose les deux sources mais c'est idiot, car tu vas avoir exactement les memes liens.

**Comment by chataigne73** [comment]
Merci d'avoir regardé, j'avais pas vu votre réponse.
À+
