### ISSUE TITLE
Faire le ménage

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#88]
Bon vue l'ampleur de l'addon maintenant faut penser a faire un rangement, je suis entrain de recoder setting pour affiche les source en catégorie mais quel catégorie?

on pourais faire film, series ect.. mais je pense plutot faire un tris genre nombre de host 
~ 2 host la liste 
~ 5 host la liste

Le but ultime c'est de diminuer le nombre de source activer par defaut.

**Comment by TmpName** [comment]
Bne idée.

Par contre pour le tri .....

Je trouve pas le nombre de host representatif, certains site HD n'ont qu'un seul host mais qui marche a 100/100. D'autres proposent youwatch/exashare/ect .. ou des hosts generallement avec la source effacée.

Un tri par qualitée (note subjectivement) ? Avec possibilitée de changer ce choix tout les mois a la mise a jour ?

Mais tu veux les desactiver pour la recherche ou la page "home" ?

**Comment by LordVenom** [comment]
Pour les 2 quand dans films nouveauter y a plus de 15 sites c'est trop perso j'utilise les 3 premiers bon ont peux en laisser entre 5 et 10max activer. Pour le tris je sais pas encore je réfléchis toujours.

**Comment by TmpName** [comment]
Ha oui je vois ce que tu veux dire.

Pkoi pas faire une sorte de "site favoris", Vstream fonctionne a la base avec une liste predefinie cutomisable par l'user.

Quand l'user va dans "toute les sources" il vois toute les sources mais vert = toujours affichees, rouge = jamais affichée, ect ... (en fait je pense que peu de monde ira voir dans le menu de configuration et que les sources desactivés ne seront jamais vu).
Et a cet endroit rajouter un emnu contextuel pour gerer les sources plus facilement.

Pour la recherche je pense que c'est mieux d'en laisser le plus possible, certaines sources ne servent a rien mais possede la vielle serie qui ne sort pas sur les autres moteurs, l'avantage de Vstream c'est sont moteur de recherche.

**Comment by LordVenom** [comment]
Je suis entrain de refaire le setting pour simplifier notre travail d'ajout suppression de source.

Pour le choix les utilisateur le font pour nous j'ai quelque retour.

3. /freebox 10,13 %
4. /frenchstream_org 8,26 %
5. /seriefr_com 5,15 %
6. /filmstreamingz_fr 4,16 %
7. /themoviedb_org  3,83 %
8. /full_stream_me 3,70 %
9. /film_illimit_fr 3,66 %
10. /streamzer_net 3,52 %

**Comment by chataigne73** [comment]
Puisque TmpName en a parlé, j'en profite pour dire qq mots de la recherche vstream. C'est vraiment une super fonctionnalité, mais serait il possible de limiter les résultats de chaque site à 2 ou 3 résultats ? Dans 95% du temps les suivants ne sont pas pertinents, et ça serait plus lisible et plus rapide

**Comment by chataigne73** [comment]
J'en profite aussi pour dire que selon moi themoviedb n'est pas le meilleur choix pour la recherche visuelle. Il liste des films qu'on ne trouve encore nulle part. (Perso j'ai  recode la fonction pour utiliser zone-telechargement, puis derrière je lance la recherche vstream ou alluc comme vous; zone-telechargement est plus fiable pour lister les films trouvables ;-) )

**Comment by TmpName** [comment]
@LordVenom la je ne comprend pas du tout, ce n'est pas du tout les sites que j'utilise le plus, et je ne pensais pas que autant de monde cherchait a voir la tv via Vstream. Faudrait voir a rendre libretv plus accessible.

Pour le coup des imports, je pensais juste rendre possible l'activation/desactivation via "afficher toute les sources" plutot que le menu de config, l'accés a l'activation/desactivation etant plus facile, moins de scrupules a tailler dans le tas pour en desactiver.

Pour @chataigne73, c'est un choix prit a la base, on pourrait filtrer les resulats (surtout que le moteur de certains site renvoient n'importe quoi en resultats) mais on prendrait le risque de filtrer un contenu utile, personnellement je prefere avoir tout les resulats puis faire defiler pour trouver le bon que de prendre le risque de ne pas trouver ma source.
Genesis filtre les sources, donc plus simple a utiliser mais tu as un petit pourcentage d'avoir un film completement different de la recherche sans pouvoir le savoir avant de le visionner et il te manquera toujours quelques sources, a cause d'une faute de frappe ou d'une syntaxe differente.
Avec Vstream, c'est plus chiant, il te faut faire le tri toi meme mais si ton stream est present, Vstream le trouvera a 100/100.
Peut etre faire 2 pages, une pour la recherche filrée et une seconde plus poussée ?

Par contre je viens de tester le moteur de recherche de zonetelechargement, et il est tres efficace, j'ai essayé toutes les series pourries que j'avais, et il a presque tout trouve.

**Comment by chataigne73** [comment]
Pour ZT, c'est surtout pour les nouveautés que c'est pertinent : les nouveautés qu'il référence sont bien les nouveautés que l'on trouve en streaming

**Comment by TmpName** [comment]
Ben justement il m'a trouve de vieux truc comme brazil (mais c'etait la nouvelle version) cosmos 1999 ou interstella de daft punk

**Comment by TmpName** [comment]
J'ai fais une petite mise a jour dans defaut.py pour eviter les imports inutiles.
Par contre je bloque pour about.py, j'ai pas osé y toucher mais suite a https://github.com/LordVenom/venom-xbmc-addons/issues/260

Y a t'il vraiment besoin de la ligne 257 dans le fichier about.py, sachant qu'il est appelle dans defaut.py a la ligne 89 (du nouveau fichier)

**Comment by TmpName** [comment]
Vu que la mise a jour est ce WE, tu as jeté un oeuil sur le fichier about.py ? Moi j'ose pas trop y toucher.

**Comment by LordVenom** [comment]
J'ai pas suivis 

ligne 89 de default
cAbout()

ligne 257 de about
self.win.getControl( self.CONTROL_TEXTBOX ).setText(text)

Dsl mais je comprend pas ce que tu veut enlever.

**Comment by TmpName** [comment]
La ligne 261 du fichier actuel sur la beta.

**Comment by TmpName** [comment]
Il aurait pas mieux valu faire l'inverse pour cabout ?
En faisant l'inverse, il ne fait le test que sur la page home, et une seule fois, la actuellement il refait des tests a chaque clic, vu que la page defaut est chargée a chaque fois.

**Comment by LordVenom** [comment]
Hum j'y est pas penser je regarde ça
