### ISSUE TITLE
libretv

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#90]
Bon depuis leur mise a jour, c'est la misere pour trouver des chaines
>>\<order\>1\</order\>\<icon\>12/02\</icon\>

Tu sais a quoi correspondent les tag order et icon ?
Le second a l'air d'etre une date ?

Les recents marchent pas mal mais les 80/100 autres sont out, et pour faire le tri actuellement .....

**Comment by LordVenom** [comment]
Aucune idée non

**Comment by TmpName** [comment]
Alors j'ai trouvé order correspond a aujourdhui/ce mois ci/anterieur
Et l'autre c'est bien la date.

V modifier le fichier pour gerer ca.

**Comment by TmpName** [comment]
Bon c'est plus clair mais les images ne s'affichent plus, ils ont chnagé l'url aussi.
