### ISSUE TITLE
Librairie.

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons-beta#91]
Je jete un oeuil pour mettre en place les librairies ou tu es contre ?
En fait c'est pas dur a mettre en place, mais effectivement sur une liste de fim/serie il n'y a pas moyen de savoir si c'est un fichier ou un stream. Apres c'est l'user qui active le truc ou pas, mais le resultat depote, moins de manips que les favoris, et tu as tout le package icone, resume, ect ... (vu que meta)

Faudra modifier les options, et rajouter une section dans home pour la gestion.

Sinon a propos de spyware, ma copine vient juste de se debarasser d'un logger, elle s'en est rendu compte apres s'etre fait pirater skype.

**Comment by LordVenom** [comment]
Comme dab tu est libre :) , j'ai tous nettoyer la mais ça ram encore je suis bon pour un format voir un rachat de ram.Surement du aussi en partis a l'install de win10 merci M$.

**Comment by TmpName** [comment]
Ha win10 et son forcing ^^, il demarre mal celui la.

Pour son virus, Elle a meme du changer sa carte bancaire, on a trouve les numeros dans les logs du logger.
Et impossible de savoir ou elle a choppé ca.

Moi perso c'est pas une fonction qui me servira (je savais meme pas que ca existait) , mais je comprend qu'elle soit sur les autres addons, c'est pas que c'est utile, mais ca augmente "l'integration de Vstream dans kodi" de maniere tres visible.

Apres je prefere demander le feu vert, si vraiment tu penses que ca peut nuire a Vstream, on zappe.
D'ailleurs une question, sur un petit systeme (style raspberry) vaut mieux plein de petits fichiers, ou peu mais gros ? Te demande ca car Vstream prend du poid.

**Comment by TmpName** [comment]
Bon j'ai commencé, ca marche pour les films, pas encore testé les series.
J'ai aussi commencé a essayer d'alleger Vstream, limiter les imports, ect ....

**Comment by LordVenom** [comment]
hum oui pas trés utile.

Note: Je suis pas en mesure de faire une mise a jour, soit ça peux attendre soit tu en lance une comme tu veut.

**Comment by TmpName** [comment]
Yep, suis d'accord avec toi, pour celui qui utilise les favoris et pas les metas ca n'a aucune utilitée, mais c'est pas mal demandé par les users (et je comprend pour ceux qui sont fan des metas, le resulat est magnifique), et c'est pas lourd, regarde la taille du fichier.

Surtout que si l'user ne sait pas ce que c'est, ni comment le mettre en place ca ne lui servira jamais, a voir une option pour activer/desactiver la librairie ?

**Comment by LordVenom** [comment]
Bon j'ai tous reinstall et je me lance dans un test d'ajout de librairie et ben ça fonctionne pas, j'ai tester genesis pour voir ça fonctionne pas non plus.Y a bien la fenêtre d'ajout, ça tourne mais dans mes films rien de neuf.Je regarderais ça plus en profondeur plus tard.

**Comment by TmpName** [comment]
Tu passe bien par "ajouter source" ? (Ca te demande de configurer un scrapper automatiquement)

**Comment by LordVenom** [comment]
Oui oui mais je sais pas encore d ou ça vient . je fini les vacances et je m y remet

**Comment by LordVenom** [comment]
Ha ok il faut ajouter un nouveau dossier, je penser que ça irais direct dans les films. mais il faut rajouter le dossier films de vstream ok par contre pk le lien vstream librairie y a les films mais pas les icones et Fanart pk ne pas renvoyer directement a l'adresse du dossier créé ?

**Comment by TmpName** [comment]
Alors la, je parle sans trop savoir, mais je pense qu'il y a plusieurs mode de fonctionnement, certains ont les infos/meta dans le meme dossier que le film, pas chez moi, c'est pour ca que pour les film je ne crée pas de repertoire mais juste un fichier, genesis crée un repertoire (mais j'avais pas compris l'utilité).

Le lien configuré dans Vstream (dans les options) est le lien a rajouter dans kodi (ajouter nouvelle sources, ect ...) Kodi le gera exactement comme tes repertoires de films.

Chez moi icones et fanart doivent etre dans la base de donnée, car je n'ai absolument rien dans mes repertoires de films.

Si tu parles du lien librairie de "home" c'est juste un explorateur de fichier, pour les modif fanart tu passes direct par la bibliotheque de kodi vu que tout le repertoire va y apparaitre.

"pk ne pas renvoyer directement a l'adresse du dossier créé ?" La j'ai pas tout compris, mais il y a gavé d'ameliorations possible, juste que j'ai pas trop eu de temps, et comme sa t'emballe pas trop ...

**Comment by LordVenom** [comment]
Bon j'ai pas réussis a faire ceux que je voulais pas grave. Je suis a la bourre pour la mise a jour dsl.

**Comment by TmpName** [comment]
Lol, pas grave, meilleurs voeux en passant ^^.
Mais durant ton absence y a plein de nouveaux probleme qui ont surgis, ton ordi va mieux ?

**Comment by LordVenom** [comment]
Merci meilleur vœux a toi aussi. Oui l ordi tourne la je tente de retrouver mes marques et voir les postes pour me tenir au courant.

**Comment by LordVenom** [comment]
J'ai juste modifier le lien home puisque xbmc créer le dossier je navigue avec xbmc dit moi ceux que tu en pense.

**Comment by TmpName** [comment]
Ha oui j'y pense jamais a ca.

Mais ca marche chez toi ou pas ? pour savoir si je continu comme ca ou si je dois mettre les films dans des repertoires ?

**Comment by LordVenom** [comment]
Chez moi le répertoire ce créer tous seul et ça marche.même les series sauf que pour lui c'est une série et pas la saison d'une série mais ça...

**Comment by TmpName** [comment]
Ben moi je fais un repertoire contenant un fichier strm par films, et les autres addons font un repertoire par film contenant le fichier strm, moi je vois pas l'utilite mais je sais que dans certaines configuration kodi peut rajouter des fichier dans le meme repertoires (eg des *.nfo) mais j'en sais pas plus, la je decouvre.

Pour les series je vais faire un repertoire par serie, et dedans tout les fichiers en vrac nommé nom_de_la_serie_SXXEXX.strm, kodi gere le tout sans problemes, deja testé (il classe lui meme par saison) Ca va eviter de voir plusieurs fois la meme serie dans les listings. J'ai meme commencé a rajouter des fonctions speciales dans util.py (pour gerer les SXXEXX, pour filtrer les resultats de recherche, ect ...) qui devraient me servir apres la mise a jour.

Mais bon, pas eu trop de temps, et me faut en priorite refaire poypi.

**Comment by TmpName** [comment]
Je viens de retester la librairie, avec l'explorateur de fichier integré a kodi, comment tu fais pour supprimer un fichier ?
A certain endroit je passe par "gerer" mais la j'ai rien du tout.

**Comment by LordVenom** [comment]
Comme pour les films de la médiateque il faut activer d'abord la suppression. Parametre-apparence-liste de fichier - "autoriser a renommer et a supprimer" ensuite tu auras l'option dans l'explorateur et aussi quand tu supprimeras depuis la médiatheque.
