### ISSUE TITLE
serie en streaming.tv

### ISSUE THREAD

**Issue by kevin465** [LordVenom/venom-xbmc-addons-beta#93]
salut tout d'abord j'adore ton plug in c'est vraiment super ! mais depuis 1 semaine j'ecoute better call saul sur seriesenstreaming.tv mais maintenant les épisodes ne s'affiche plus... ?

**Comment by TmpName** [comment]
Ha merde j'avais vu le doublon dsl.
cf https://github.com/LordVenom/venom-xbmc-addons/issues/291
