### ISSUE TITLE
Menu Vstream

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons-beta#94]
Sur la beta je trouve des difficultés avec le menu, je ne peux pas visualiser toutes les rubriques ca passe directement de General a Librairie.
En plus la recherche similaire ne fait pas un balayge sur certains sites.

**Comment by TmpName** [comment]
Tu fais au clavier pour te deplacer ?
Tu vois combien de rubriques ?

**Comment by LordVenom** [comment]
La fonction recherche similaire vas sauter pour le moment.

**Comment by TmpName** [comment]
La j'ai pas compris, tu penses a quoi LordVenom ?
Il peut y avoir un bug dans le fichier setting qui peut provoquer ca ?

**Comment by LordVenom** [comment]
Perso j'ai pas de bug mais si c'est un bug dans les paramètre de l'addon y a que setting.xml qui le gére. Peux être met changement ne sont pas compatible avec de vielle version xbmc.

**Comment by arzaz** [comment]
Bonjour TmpName,

Voici mes reponses:
Tu fais au clavier pour te deplacer ? J'utlise la télécommande, car vstream est installé sur ma box Prismcube
 Tu vois combien de rubriques ? General - Plugins on/off 1/2 - Plugins on/off 2/2 - Accueil.
A l'ouverture du Menu j'ai directement accès a la rubrique General mais quand j'essai de deplacer le curseur vesr plugins on/off 1/2 il saute directement vers Librairie?

**Comment by TmpName** [comment]
Alors la je vois pas, je vais essayer de te faire une version light du fichier pour faire des tests, Ca te le fait que avec cet addon ?

**Comment by arzaz** [comment]
Seulement lorsque j'installe la beta, mais non pas avec la version finale

**Comment by TmpName** [comment]
Je viens de faire une petite mise a jour, mais ca m'etonnerais que le bug vienne de ca.
Essaye ce fichier a la place de setting.xml
>> http://pastebin.com/MugvTCvf

Ca va te supprimer les options pour les sites.

Apres si tu veux desactiver/activer des bout de code c'est

**Comment by arzaz** [comment]
Avec la version light de settings.xml ca marche bien mais il suffit de désactiver  le problème réapparait?

**Comment by TmpName** [comment]
En fait je te donnes plusieurs version avec  a chaque fois une partie desactivée jusqu'a trouver la partie en question par elimination.

Pour le moment on sait que ca vient de la partie "site" vu que c'est celle qui été desactivé dans la version pastebin

2 nouvelles versions a tester.
http://pastebin.com/RyRKvgVF
et
http://pastebin.com/dcN6AzS8

La premiere je desactive le promier onglet site, dans la seconde le second.

**Comment by LordVenom** [comment]
Mince les changements apporter ne sont pas compatible sur toutes les versions, pas trés logique mais bon.A voir si tu trouve les lignes qui bug.

**Comment by TmpName** [comment]
C'est clair que la c'est con, le probleme c'est que comme d'hab j'ai pas le prbs chez moi pour depanner.
Et je ne vois pas ce qu'il y a de magique dans la nouvelle version qui pourrait ne pas passer.

**Comment by arzaz** [comment]
Avec les 02 versions http://pastebin.com/RyRKvgVF et http://pastebin.com/dcN6AzS8 J'arrive a accéder au plugins on/off mais sans toutefois changer ou déplacer le curseur et le menu se fige a ce stade là? Je crois que c'est un problème d'affichage?

**Comment by TmpName** [comment]
Ok, bon ben la, pas de bol, en fait LordVenom avait fait un menu ou les options se cachaient pour eviter d'avoir 200 lignes d'options inutiles, apparement pas compatible sur toutes les versions.

Tu as quoi deja comme systeme/versions ? Pas moyen de mettre quelque chose a jour ?

**Comment by arzaz** [comment]
J'utilise vstream sur Prismcube avec la version gotham 13.2

**Comment by TmpName** [comment]
Bon j'ai jeté un oeuil vite fait, pas de kodi 14 apparement.

Je sais pas si il y a moyen de mettre du code dans le fichier xml qui change selon la version de kodi ?

**Comment by LordVenom** [comment]
Faudra revenir sur une vielle version d'hommage.

**Comment by TmpName** [comment]
Et y a pas moyen de mettre du code dans le fichier xml, qui chargerait une configuration plutot qu'une autre ?

**Comment by LordVenom** [comment]
Ha non pas que je sache et ça compliquerais encore le code.

**Comment by LordVenom** [comment]
@arzaz  tu peux tester la nouvelle version stp.

**Comment by arzaz** [comment]
Extraordinaire, c

**Comment by TmpName** [comment]
Ce serait pas mieux de remplacer "recherche 1" "recherche 2" par "films" "serie" ??

**Comment by LordVenom** [comment]
Dans la recherche j'ai bien retranscrit recherche 1:, recherche 2: donc ça reste valide.

**Comment by TmpName** [comment]
C'est pas que c'est faux c'est juste que pour quelqu'un qui n'a pas l'autre page en tete, c'est plutot obscurs, faut se souvenir que "recherche 1" correspond aux films.

**Comment by LordVenom** [comment]
Perso ma recherche 1 c'est toute mes source préférer films et serie confondu, la 2 ceux qui ont le plus de host. et j'utilise pas les 2 autres.

**Comment by TmpName** [comment]
Ha oui, c'est vrai j'avais oublie que c'etait customisable, et vu que j'ai tout laisse par defaut ....
