### ISSUE TITLE
Masquer les sites

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons-beta#96]
Addon master, codeur de GenesisFr pense que si nous modifions les noms de sites il seras plus dur pour eux de recorder leur sites pour nous empêcher l'acces.

En gros si nous mettons ça en oeuvre vous n’aurez plus full-stream, streamzer ect.. mais des nom sites1, sites2

Merci de me donnez vos impression.

**Comment by chataigne73** [comment]
salut
je pense que ce gars est parano
j'ai pas encore vu de changement dans le code des sites parce que nous on vient piocher chez eux, et au pire c'est pas bien compliqué à contourner

et d'un autre côté même si on cachait le nom des sites c'est pas bien compliqué pour eux d'aller voir dans nos github pour savoir où on pioche

donc je vote contre ... c'est useless

**Comment by TmpName** [comment]
Lol, pas mieux.

On a rien de secret, et c'est pas dur pour eux de verifier chez nous, ils mettent leurs sites a jour de la meme maniere que nous nos fichiers sites, c'est pas une guerre ouverte.

**Comment by Kodigoal** [comment]
C'est vrai qu'un coup d'oeil du côté des fichiers sites .py suffirait pour les sites à voir
qu'ils sont utilisés ici.
Donc vraiment si ses sites veulent bloquer l'accés , ne pas les nommer dans l'interface ne servira à pas grand chose.
Et d'un point de vue perso, j'aime bien savoir sur quel site je suis :-)
Après ont-ils les moyens de bloquer à 100% l'accès si vraiment ils veulent qu'on
passe seulement par leur site?

**Comment by LordVenom** [comment]
Oui et non en principe tout ceux qui et coder peux être decoder mais ça peux etre trop lourd pour vstream, Enfin si il abuse sur le bloquage des utilisateurs de leur site le sentirons aussi et ils perdrons des visiteurs.
Un peux comme c'est site qui te bloque si tu as Adblock, tu désactive pas Adblock tu quit leur site.
